import { StyleSheet } from "react-native";
import { colors } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  head: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  back: { fontSize: 16, color: colors.ink, fontWeight: "700", width: 48 },
  headTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 20,
    fontWeight: "800",
    color: colors.ink,
  },
  headRight: { width: 48 },
  content: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 48 },

  // 汇总卡片：第一行两卡，第二行单卡更矮
  summaryRow: { flexDirection: "row", gap: 8 },
  summaryCard: {
    flex: 1,
    backgroundColor: colors.card,
    borderRadius: 18,
    borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    paddingVertical: 14,
    paddingHorizontal: 10,
    alignItems: "center",
  },
  summaryLabel: { fontSize: 12, color: colors.muted, fontWeight: "600" },
  summaryValue: { marginTop: 5, fontSize: 19, fontWeight: "800" },
  summarySub: { marginTop: 2, fontSize: 10, color: colors.muted },
  sumGreen: { color: colors.ready },
  sumRed: { color: colors.danger },
  sumBrand: { color: colors.brandHot },
  summarySingle: { marginTop: 8 },
  /* 我需要支付：蓝色主调大框，与上一行同高（同 padding / 同三行结构） */
  summaryCardSlim: {
    backgroundColor: colors.brandHot,
    borderRadius: 18,
    borderCurve: "continuous",
    paddingVertical: 14,
    paddingHorizontal: 10,
    alignItems: "center",
    shadowColor: colors.brandHot,
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  slimLabel: { fontSize: 12, fontWeight: "600", color: "rgba(255,255,255,0.92)" },
  slimValue: { marginTop: 5, fontSize: 19, fontWeight: "800", color: "#fff" },
  slimSub: { marginTop: 2, fontSize: 10, color: "rgba(255,255,255,0.85)" },

  // 入口卡片（消费明细 / 结算方案）
  cardLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: colors.card,
    borderRadius: 22,
    borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
    marginBottom: 10,
  },
  cardIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    borderCurve: "continuous",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 21,
  },
  cardBody: { flex: 1, minWidth: 0 },
  cardTitle: { fontSize: 15, fontWeight: "800", color: colors.ink },
  cardSub: { marginTop: 3, fontSize: 12, color: colors.muted },
  cardArrow: { fontSize: 18, color: "#c9c9c9", fontWeight: "700" },

  // 操作按钮（消费明细页的通栏「记一笔」也复用 primaryBtn）
  actionRow: { flexDirection: "row", gap: 8, marginTop: 14 },
  primaryBtn: {
    flex: 1,
    backgroundColor: colors.brandHot,
    borderRadius: 999,
    borderCurve: "continuous",
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  primaryBtnText: { color: "#fff", fontSize: 15, fontWeight: "800" },
  ghostBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    borderRadius: 999,
    borderCurve: "continuous",
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  ghostBtnText: { color: colors.ink, fontSize: 14, fontWeight: "700" },

  section: { marginTop: 22 },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  sectionTitle: { fontSize: 16, fontWeight: "800", color: colors.ink },
  sectionAdd: { marginLeft: "auto", padding: 4 },
  sectionAddText: { fontSize: 13, fontWeight: "700", color: colors.brandHot },
  sectionHint: { fontSize: 12, color: colors.muted, marginBottom: 10 },

  // 同行人
  memberWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  memberChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#F5F8FB",
    borderRadius: 999,
    borderCurve: "continuous",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: colors.line,
  },
  memberChipMe: { borderColor: colors.brand, backgroundColor: colors.brandSoft },
  memberName: { fontSize: 13, fontWeight: "700", color: colors.ink },
  memberMeTag: { fontSize: 10, color: colors.brandHot, fontWeight: "700" },
  memberBal: { marginLeft: 2, fontSize: 12, fontWeight: "800" },
  memberEmpty: { fontSize: 13, color: colors.muted },

  // 费用
  expenseCard: {
    backgroundColor: colors.card,
    borderRadius: 22,
    borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    marginBottom: 10,
  },
  expenseHead: { flexDirection: "row", alignItems: "center" },
  expenseTitle: { flex: 1, fontSize: 15, fontWeight: "700", color: colors.ink },
  expenseAmount: { fontSize: 16, fontWeight: "800", color: colors.ink },
  expenseMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
  },
  expenseMetaText: { fontSize: 12, color: colors.muted },
  expenseSplit: {
    marginTop: 8,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  splitChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#F5F8FB",
    borderRadius: 12,
    borderCurve: "continuous",
    paddingVertical: 3,
    paddingHorizontal: 7,
  },
  splitChipText: { fontSize: 11, color: colors.muted, fontWeight: "600" },

  // 消费明细页
  totalBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginBottom: 12,
  },
  totalBarCount: { fontSize: 16, fontWeight: "800", color: colors.ink },

  // 结算方案页
  sectionTitleRowTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.ink,
    marginBottom: 10,
  },
  balanceCard: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 22,
    borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 2,
  },
  balanceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  balanceName: { flex: 1, fontSize: 13, fontWeight: "600", color: colors.ink },
  balanceMeTag: { fontSize: 10, color: colors.brandHot, fontWeight: "700" },
  balanceVal: { fontSize: 14, fontWeight: "800" },
  balanceEmpty: {
    fontSize: 13,
    color: colors.muted,
    paddingVertical: 16,
    textAlign: "center",
  },

  // 结算方案
  flowCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: colors.card,
    borderRadius: 22,
    borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    marginBottom: 10,
  },
  flowPerson: { flex: 1, alignItems: "center", minWidth: 0 },
  flowName: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: "600",
    color: colors.ink,
    maxWidth: 72,
  },
  flowArrow: { alignItems: "center", gap: 2 },
  flowAmount: { fontSize: 14, fontWeight: "800", color: colors.brandHot },
  flowUnit: { fontSize: 10, color: colors.muted, fontWeight: "600" },
  /* 已支付勾勾按钮：灰 = 未付，绿 = 已付，可来回切换 */
  paidBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: "#d5d5d5",
    backgroundColor: "#f7f7f7",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "auto",
    flexShrink: 0,
  },
  paidBtnDone: {
    backgroundColor: colors.ready,
    borderColor: colors.ready,
  },
  paidBtnText: { fontSize: 16, fontWeight: "900", color: "#b8b8b8" },
  paidBtnTextDone: { color: "#fff" },
  emptyBox: {
    backgroundColor: "#F5F8FB",
    borderRadius: 22,
    borderCurve: "continuous",
    padding: 20,
    alignItems: "center",
  },
  emptyText: { fontSize: 13, color: colors.muted, textAlign: "center", lineHeight: 19 },
  emptyHint: { fontSize: 12, color: "#B9C2CC", marginTop: 6, textAlign: "center" },

  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  error: { color: colors.danger, fontSize: 15, textAlign: "center" },
  retry: {
    marginTop: 16,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    borderCurve: "continuous",
  },
  retryText: { color: colors.brandHot, fontWeight: "700" },
});

export const modalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: colors.bg,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderCurve: "continuous",
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 40,
  },
  grabber: {
    alignSelf: "center",
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#E3E8EF",
    marginBottom: 14,
  },
  sheetTitle: { fontSize: 18, fontWeight: "800", color: colors.ink, marginBottom: 14 },
  fieldLabel: { fontSize: 13, fontWeight: "700", color: colors.muted, marginBottom: 6, marginTop: 10 },
  input: {
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    borderRadius: 16,
    borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.ink,
  },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: "#F5F8FB",
  },
  chipOn: { borderColor: colors.brandHot, backgroundColor: colors.brandSoft },
  chipText: { fontSize: 13, fontWeight: "700", color: colors.ink },
  chipTextOn: { color: colors.brandHot },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 14,
  },
  cancelText: { color: colors.muted, fontSize: 15, fontWeight: "700", padding: 8 },
  saveBtn: {
    backgroundColor: colors.brandHot,
    borderRadius: 999,
    borderCurve: "continuous",
    paddingVertical: 13,
    paddingHorizontal: 28,
  },
  saveBtnDisabled: { opacity: 0.45 },
  saveText: { color: "#fff", fontSize: 15, fontWeight: "800" },
});
