import { StyleSheet } from "react-native";
import { colors } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "transparent" },
  content: { padding: 20, paddingBottom: 40 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  badge: { color: colors.brand, fontWeight: "700", fontSize: 12 },
  title: { marginTop: 6, fontSize: 24, fontWeight: "800", color: colors.ink },
  meta: { marginTop: 8, color: colors.muted, fontSize: 14 },
  tab: {
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    borderRadius: 30, borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  tabOn: { backgroundColor: colors.brand, borderColor: colors.brand },
  tabText: { fontWeight: "600", color: colors.ink, fontSize: 13 },
  tabTextOn: { color: "#fff" },
  summary: {
    backgroundColor: colors.card,
    borderRadius: 22, borderCurve: "continuous",
    padding: 12,
    color: colors.ink,
    marginBottom: 12,
    lineHeight: 20,
  },
  item: {
    backgroundColor: colors.card,
    borderRadius: 22, borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    padding: 12,
    marginBottom: 8,
  },
  itemType: { fontSize: 12, color: colors.brand, fontWeight: "600" },
  itemName: { marginTop: 2, fontSize: 16, fontWeight: "700", color: colors.ink },
  itemDesc: { marginTop: 4, fontSize: 13, color: colors.muted },
  mapTitle: { fontWeight: "800", color: colors.ink, marginBottom: 8 },
  error: { color: colors.danger },
  collabBox: {
    marginTop: 14,
    backgroundColor: colors.card,
    borderRadius: 18,
    borderCurve: "continuous",
    padding: 12,
    borderWidth: 1,
    borderColor: colors.line,
  },
  collabTitle: { fontSize: 13, fontWeight: "700", color: colors.ink },
  collabAvatarRow: { marginTop: 10, flexDirection: "row", flexWrap: "wrap", gap: 10 },
  collabAvatarChip: { flexDirection: "row", alignItems: "center", gap: 6, maxWidth: 160 },
  collabAvatarName: { fontSize: 12, color: colors.ink, flexShrink: 1 },
  joinBtn: {
    marginTop: 14,
    backgroundColor: colors.brand,
    borderRadius: 22,
    borderCurve: "continuous",
    paddingVertical: 12,
    alignItems: "center",
  },
  joinBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  pasteWrap: { flex: 1, padding: 24, justifyContent: "center" },
  pasteTitle: { fontSize: 22, fontWeight: "800", color: colors.ink },
  pasteSub: {
    marginTop: 8,
    fontSize: 14,
    color: colors.muted,
    lineHeight: 20,
  },
  pasteInput: {
    marginTop: 18,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 18,
    borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: colors.ink,
    minHeight: 88,
    textAlignVertical: "top",
  },
  pasteBtn: {
    marginTop: 14,
    backgroundColor: colors.brand,
    borderRadius: 22,
    borderCurve: "continuous",
    paddingVertical: 13,
    alignItems: "center",
  },
  pasteBtnOutline: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: colors.brand,
    borderRadius: 22,
    borderCurve: "continuous",
    paddingVertical: 13,
    alignItems: "center",
  },
  pasteBtnDisabled: { opacity: 0.45 },
  pasteBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  pasteBtnOutlineText: { color: colors.brandHot, fontWeight: "700", fontSize: 15 },
});
