import { StyleSheet } from "react-native";
import { colors, cardShadow } from "../../theme";
import { GRID_GAP } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#eef2f7" },
  mapLayer: { ...StyleSheet.absoluteFill, zIndex: 0 },
  topOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 16,
    paddingBottom: 8,
    zIndex: 40,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 30, borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.92)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    ...cardShadow,
  },
  backText: { fontSize: 22, color: colors.ink, fontWeight: "300", marginTop: -2 },
  shareHeadBtn: {
    height: 40,
    borderRadius: 20,
    borderCurve: "continuous",
    backgroundColor: colors.brand,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
    ...cardShadow,
  },
  shareHeadText: { fontSize: 13, fontWeight: "800", color: "#fff" },
  topCityBlock: { flex: 1, paddingTop: 4 },
  topCityName: { fontSize: 20, fontWeight: "800", color: colors.ink },
  topCitySub: { fontSize: 12, color: colors.muted, marginTop: 2 },
  filterBar: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 12,
  },
  filterScroll: {
    paddingHorizontal: 16,
    gap: 10,
    flexDirection: "row",
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.95)",
    borderRadius: 32, borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 10,
    ...cardShadow,
  },
  filterChipOn: {
    backgroundColor: colors.ink,
  },
  filterLabel: { fontSize: 14, fontWeight: "700", color: colors.ink },
  filterLabelOn: { color: "#fff" },
  sheetMain: {
    flex: 1,
    minHeight: 0,
  },
  sheetScroll: {
    flex: 1,
    minHeight: 0,
  },
  /** 编辑态：列表独占滚动区（替代 ScrollView），拖拽列表作为唯一滚动容器 */
  editWrap: {
    flex: 1,
    minHeight: 0,
    paddingHorizontal: 20,
    paddingTop: 4,
  },
  /** FadeSwitch 包裹层也要占满，DraggableFlatList 才能拿到有界高度 */
  editListGrow: {
    flex: 1,
    minHeight: 0,
  },
  sheetList: {
    paddingHorizontal: 20,
    paddingBottom: 64,
  },
  content: { paddingHorizontal: 16, paddingBottom: 48 },
  title: { fontSize: 24, fontWeight: "800", color: colors.ink, marginTop: 16 },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.bg,
    padding: 24,
  },
  meta: { marginTop: 8, fontSize: 14, color: colors.muted, lineHeight: 20 },
  actions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 8,
  },
  actionBtn: {
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    borderRadius: 30, borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  actionPrimary: {
    backgroundColor: colors.brand,
    borderColor: colors.brand,
  },
  actionText: { fontSize: 13, fontWeight: "600", color: colors.ink },
  actionPrimaryText: { fontSize: 13, fontWeight: "700", color: "#fff" },
  shareBanner: {
    marginHorizontal: 16,
    marginBottom: 8,
    backgroundColor: colors.brand,
    borderRadius: 22,
    borderCurve: "continuous",
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  shareBannerTitle: { fontSize: 16, fontWeight: "800", color: "#fff" },
  shareBannerSub: {
    marginTop: 4,
    fontSize: 12,
    color: "rgba(255,255,255,0.92)",
    lineHeight: 16,
  },
  shareBannerCta: {
    fontSize: 14,
    fontWeight: "800",
    color: "#fff",
  },
  shareMsg: {
    marginTop: 0,
    marginBottom: 4,
    paddingHorizontal: 20,
    fontSize: 12,
    color: colors.ready,
  },
  section: { marginTop: 16 },
  collabSection: {
    marginTop: 4,
    marginBottom: 12,
  },
  collabSectionBottom: {
    marginTop: 0,
    marginBottom: 6,
    paddingHorizontal: 16,
  },
  collabShell: {
    backgroundColor: "#fff",
    borderRadius: 999,
    borderCurve: "continuous",
    overflow: "hidden",
    ...cardShadow,
  },
  collabShellCollapsed: {
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  collabShellExpanded: {
    borderRadius: 28,
    paddingVertical: 10,
    paddingHorizontal: 6,
  },
  collabHeader: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.muted,
    paddingHorizontal: 10,
    marginBottom: 6,
  },
  collabPeekRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  collabPeekAvatar: {
    zIndex: 1,
  },
  collabPeekOverlap: {
    marginLeft: -10,
  },
  collabPeekLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: colors.ink,
  },
  collabScroll: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 6,
  },
  collabChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#EEF6FC",
    borderRadius: 999,
    borderCurve: "continuous",
    paddingVertical: 6,
    paddingHorizontal: 10,
    maxWidth: 136,
  },
  collabTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  collabName: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.ink,
    lineHeight: 18,
  },
  collabRole: {
    fontSize: 11,
    color: colors.muted,
    marginTop: 1,
  },
  routeSection: {
    marginTop: 4,
    marginBottom: 12,
  },
  mapPlaceholder: {
    height: 220,
    borderRadius: 22, borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  mapPlaceholderText: { fontSize: 12, color: colors.muted },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.ink,
    marginBottom: 10,
  },
  daySection: {
    marginTop: 4,
  },
  dayTabs: { marginTop: 16, marginBottom: 8 },
  dayTab: {
    backgroundColor: colors.card,
    borderRadius: 30, borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: colors.line,
  },
  dayTabOn: { backgroundColor: colors.brand, borderColor: colors.brand },
  dayTabText: { fontSize: 13, fontWeight: "600", color: colors.ink },
  dayTabTextOn: { color: "#fff" },
  regen: { alignSelf: "flex-start", marginBottom: 12 },
  regenText: { color: colors.brand, fontWeight: "600", fontSize: 13 },
  summaryBox: {
    backgroundColor: colors.card,
    borderRadius: 22, borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    marginBottom: 14,
  },
  summaryLabel: { fontSize: 12, color: colors.brand, fontWeight: "700" },
  summaryText: { marginTop: 4, fontSize: 14, color: colors.ink, lineHeight: 20 },
  item: {
    backgroundColor: colors.card,
    borderRadius: 22, borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    marginBottom: 10,
  },
  itemCompact: {
    backgroundColor: colors.card,
    borderRadius: 22, borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    marginBottom: 10,
  },
  feedCard: {
    backgroundColor: colors.card,
    borderRadius: 24, borderCurve: "continuous",
    marginBottom: 12,
    overflow: "hidden",
  },
  feedRow: {
    flexDirection: "row",
    padding: 12,
    gap: 12,
  },
  feedThumbWrap: {
    width: 88,
    height: 88,
    borderRadius: 20, borderCurve: "continuous",
    overflow: "hidden",
    backgroundColor: "#eef2f7",
  },
  feedThumb: {
    width: 88,
    height: 88,
    borderRadius: 20, borderCurve: "continuous",
  },
  feedThumbEmoji: {
    fontSize: 32,
    textAlign: "center",
    lineHeight: 88,
  },
  feedBody: { flex: 1, minWidth: 0 },
  feedTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.ink,
    lineHeight: 22,
  },
  feedTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 6,
    alignItems: "center",
  },
  feedTag: {
    borderRadius: 16, borderCurve: "continuous",
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  feedTagText: { fontSize: 11, fontWeight: "700" },
  feedTagMuted: {
    backgroundColor: "#f3f4f6",
    borderRadius: 16, borderCurve: "continuous",
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  feedTagMutedText: { fontSize: 11, color: colors.muted },
  feedDesc: {
    marginTop: 8,
    fontSize: 13,
    color: colors.muted,
    lineHeight: 19,
  },
  feedExpand: { color: colors.brand, fontWeight: "600" },
  feedMetaRow: { flexDirection: "row", gap: 10, marginTop: 8 },
  feedMeta: { fontSize: 12, color: colors.muted },
  feedRoute: { paddingHorizontal: 12, paddingBottom: 12 },
  itemDetailCta: {
    marginTop: 10,
    fontSize: 13,
    fontWeight: "700",
    color: colors.brandHot,
  },
  itemDescPreview: {
    marginTop: 6,
    fontSize: 13,
    color: colors.muted,
    lineHeight: 18,
  },
  itemOff: { opacity: 0.5 },
  itemHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  itemType: { fontSize: 12, color: colors.brand, fontWeight: "600" },
  itemAction: { fontSize: 12, color: colors.brandHot, fontWeight: "600" },
  itemName: { fontSize: 16, fontWeight: "700", color: colors.ink },
  itemDesc: { marginTop: 4, fontSize: 13, color: colors.muted, lineHeight: 18 },
  itemMetaRow: { flexDirection: "row", gap: 10, marginTop: 6 },
  itemMeta: { fontSize: 12, color: colors.muted },
  transport: { marginTop: 8, fontSize: 12, color: colors.muted },
  alts: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 10 },
  altsLabel: { fontSize: 12, color: colors.muted, alignSelf: "center" },
  altChip: {
    fontSize: 12,
    color: colors.brandHot,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 18, borderCurve: "continuous",
    overflow: "hidden",
  },
  budget: {
    marginTop: 22,
    backgroundColor: colors.card,
    borderRadius: 24, borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
  },
  budgetRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  budgetLabel: { color: colors.muted, fontSize: 13 },
  budgetVal: { fontWeight: "600", color: colors.ink },
  budgetTotal: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
    paddingTop: 10,
    marginTop: 4,
    marginBottom: 0,
  },
  budgetHint: { fontSize: 12, color: colors.muted },
  budgetTotalVal: { fontSize: 22, fontWeight: "800", color: colors.brand },
  parallelRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: GRID_GAP,
  },
  parallelCol: {
    flex: 1,
    minWidth: 0,
  },
  parallelTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.ink,
    marginBottom: 8,
  },
  parallelHint: {
    fontSize: 11,
    color: colors.muted,
    marginBottom: 6,
    marginTop: -4,
  },
  parallelEmpty: {
    fontSize: 12,
    color: colors.muted,
    paddingVertical: 10,
  },
  compactCard: {
    backgroundColor: colors.card,
    borderRadius: 20, borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  compactSource: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.brand,
    marginBottom: 2,
  },
  compactTitle: {
    fontWeight: "700",
    color: colors.ink,
    fontSize: 13,
    lineHeight: 18,
  },
  compactAccent: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: "600",
    color: colors.ready,
  },
  generating: { marginTop: 16, fontSize: 16, fontWeight: "600", color: colors.ink },
  genRoot: {
    flex: 1,
    backgroundColor: "#eef2f7",
  },
  genMapWrap: {
    height: 280,
    backgroundColor: "#eef2f7",
    overflow: "hidden",
  },
  genBodyScroll: { flex: 1 },
  genBody: {
    paddingHorizontal: 16,
    paddingTop: 0,
    paddingBottom: 32,
  },
  genHero: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.ink,
    marginBottom: 12,
    paddingHorizontal: 20,
    marginTop: 4,
  },
  genPhaseRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingHorizontal: 20,
  },
  genPhaseItem: { flex: 1, alignItems: "center" },
  genPhaseDot: {
    width: 8,
    height: 8,
    borderRadius: 14, borderCurve: "continuous",
    backgroundColor: colors.line,
    marginBottom: 4,
  },
  genPhaseDotDone: { backgroundColor: colors.brand },
  genPhaseDotActive: {
    backgroundColor: colors.brand,
    transform: [{ scale: 1.35 }],
  },
  genPhaseLabel: { fontSize: 9, color: colors.muted, textAlign: "center" },
  genPhaseLabelOn: { color: colors.brandHot, fontWeight: "700" },
  genStreamBubble: {
    backgroundColor: colors.card,
    borderRadius: 28, borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
    minHeight: 200,
  },
  genStreamRole: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.brand,
    marginBottom: 8,
  },
  genStreamStatus: {
    fontSize: 14,
    color: colors.muted,
    marginBottom: 12,
    lineHeight: 20,
  },
  genStreamScroll: { maxHeight: 320 },
  genStreamText: {
    fontSize: 15,
    color: colors.ink,
    lineHeight: 24,
  },
  genStreamTyping: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  genStreamTypingText: { fontSize: 13, color: colors.muted },
  genStreamCursor: {
    fontSize: 16,
    color: colors.brand,
    marginTop: 8,
    fontWeight: "300",
  },
  actionAi: {
    borderColor: colors.brand,
    backgroundColor: colors.brandSoft,
  },
  actionPost: {
    borderColor: colors.brand,
    backgroundColor: colors.brand,
  },
  hint: { marginTop: 8, fontSize: 13, color: colors.muted, textAlign: "center" },
  error: { color: colors.danger, fontSize: 16, textAlign: "center" },
  retry: {
    marginTop: 16,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20, borderCurve: "continuous",
  },
  retryText: { color: colors.brandHot, fontWeight: "700" },

  // ---- 地图选点提示条 ----
  pickBar: {
    position: "absolute",
    left: 16,
    right: 16,
    zIndex: 30,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: colors.ink,
    borderRadius: 22,
    borderCurve: "continuous",
    paddingHorizontal: 16,
    paddingVertical: 12,
    ...cardShadow,
  },
  pickBarText: {
    flex: 1,
    color: "#fff",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
  },
  pickCancelText: { color: "#ffd9d2", fontSize: 13, fontWeight: "700" },

  // ---- 天头部：重新生成 / 添加地点 / 编辑 ----
  dayHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  dayHeadSpacer: { flex: 1 },
  dayHeadLink: { paddingVertical: 4, paddingRight: 8 },
  dragHint: { fontSize: 11, color: colors.muted, marginBottom: 10, marginTop: -4 },
  dayHeadBtn: {
    borderRadius: 18,
    borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    paddingHorizontal: 12,
    paddingVertical: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  dayHeadBtnOn: { backgroundColor: colors.brand, borderColor: colors.brand },
  dayHeadBtnText: { fontSize: 13, fontWeight: "600", color: colors.ink },
  dayHeadBtnTextOn: { color: "#fff" },

  // ---- 删除按钮（编辑态，盖在卡片右上角） ----
  deleteBtn: {
    position: "absolute",
    top: 8,
    right: 8,
    zIndex: 5,
    width: 26,
    height: 26,
    borderRadius: 13,
    borderCurve: "continuous",
    backgroundColor: "rgba(244,67,54,0.92)",
    alignItems: "center",
    justifyContent: "center",
  },
  deleteBtnText: {
    fontSize: 13,
    lineHeight: 15,
    fontWeight: "700",
    color: "#fff",
  },

  // ---- AddSpotSheet ----
  spotKav: { flex: 1, justifyContent: "flex-end" },
  spotSearchInput: {
    backgroundColor: "#F4F7F5",
    borderRadius: 14,
    borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 14,
    color: colors.ink,
    marginBottom: 10,
  },
  addRoot: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  addBackdrop: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "transparent",
  },
    addSheet: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 26,
      borderCurve: "continuous",
      borderTopRightRadius: 26,
      maxHeight: "72%",
      paddingHorizontal: 20,
      paddingTop: 16,
    },
    /** 包住弹层的键盘避让容器：键盘弹出时把整个面板顶到键盘上方 */
    addKavWrap: { flex: 1, justifyContent: "flex-end" },
  addHead: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  addHeadMain: { flex: 1, minWidth: 0 },
  addTitle: { fontSize: 17, fontWeight: "800", color: colors.ink },
  addSub: { marginTop: 4, fontSize: 12, color: colors.muted, lineHeight: 17 },
  addClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderCurve: "continuous",
    backgroundColor: "#f3f4f6",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  addCloseText: { fontSize: 15, color: colors.ink },
  addTypeRow: { flexDirection: "row", gap: 8, marginBottom: 12 },
  addTypeChip: {
    borderRadius: 20,
    borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: "#f3f4f6",
    borderWidth: 1,
    borderColor: colors.line,
  },
  addTypeChipOn: { backgroundColor: colors.brand, borderColor: colors.brand },
  addTypeText: { fontSize: 13, fontWeight: "600", color: colors.ink },
  addTypeTextOn: { color: "#fff" },
  addLoading: { paddingVertical: 32, alignItems: "center" },
  addList: { flexGrow: 0, maxHeight: 300 },
  addRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
  },
  addRowBody: { flex: 1, minWidth: 0 },
  addRowName: { fontSize: 15, fontWeight: "700", color: colors.ink },
  addRowSub: { marginTop: 2, fontSize: 12, color: colors.muted },
  addRowDist: { fontSize: 12, color: colors.muted },
  addRowArrow: { fontSize: 18, fontWeight: "700", color: colors.brand },
  addEmpty: { paddingVertical: 24, alignItems: "center" },
  addEmptyText: { fontSize: 13, color: colors.muted },
  addCustom: { marginTop: 12 },
  addCustomBtn: {
    borderRadius: 22,
    borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.brand,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: colors.brandSoft,
  },
  addCustomBtnText: { fontSize: 14, fontWeight: "700", color: colors.brandHot },
  addCustomForm: { flexDirection: "row", gap: 8 },
  addCustomInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 18,
    borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: colors.ink,
    backgroundColor: "#fff",
  },
  addCustomConfirm: {
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: colors.brand,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  addCustomConfirmText: { fontSize: 14, fontWeight: "700", color: "#fff" },

  // ---- AddCitySheet ----
  citySection: { marginTop: 12 },
  citySectionLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.muted,
    marginBottom: 8,
  },
  citySearchInput: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 18,
    borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: colors.ink,
    backgroundColor: "#fff",
    marginBottom: 10,
  },
  citySheetScroll: { maxHeight: 220, flexGrow: 0 },
  cityGroup: { marginBottom: 10 },
  // 面板主体滚动容器（AddCitySheet 单一滚动适配）
  cityBodyScroll: {
    flexGrow: 0,
    flexShrink: 1,
  },
  cityLetter: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.brand,
    marginBottom: 6,
  },
  cityChips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  cityChip: {
    borderRadius: 18,
    borderCurve: "continuous",
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: "#f3f4f6",
    borderWidth: 1,
    borderColor: colors.line,
  },
  cityChipOn: { backgroundColor: colors.brand, borderColor: colors.brand },
  cityChipText: { fontSize: 13, fontWeight: "600", color: colors.ink },
  cityChipTextOn: { color: "#fff" },
  cityDayWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  cityConfirm: {
    marginTop: 14,
    borderRadius: 22,
    borderCurve: "continuous",
    backgroundColor: colors.brand,
    paddingVertical: 13,
    alignItems: "center",
  },
  cityConfirmDisabled: { opacity: 0.5 },
  cityConfirmText: { fontSize: 15, fontWeight: "800", color: "#fff" },
  cityManageRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
  },
  cityManageName: { flex: 1, fontSize: 15, fontWeight: "700", color: colors.ink },
  cityManageSub: { fontSize: 12, color: colors.muted },
  cityManageDel: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderCurve: "continuous",
    backgroundColor: "rgba(244,67,54,0.92)",
    alignItems: "center",
    justifyContent: "center",
  },
  cityManageDelText: { fontSize: 13, lineHeight: 15, fontWeight: "700", color: "#fff" },
  cityEmpty: { paddingVertical: 20, alignItems: "center" },
  cityEmptyText: { fontSize: 13, color: colors.muted },
});
