import { StyleSheet } from "react-native";
import { colors, cardShadow } from "../../theme";
import { GRID_GAP } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#eef2f7" },
  mapLayer: { ...StyleSheet.absoluteFill, zIndex: 0 },
  topOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 16,
    paddingBottom: 8,
    zIndex: 10,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.92)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    ...cardShadow,
  },
  backText: { fontSize: 22, color: colors.ink, fontWeight: "300", marginTop: -2 },
  topCityBlock: { flex: 1, paddingTop: 4 },
  topCityName: { fontSize: 20, fontWeight: "800", color: colors.ink },
  topCitySub: { fontSize: 12, color: colors.muted, marginTop: 2 },
  filterBar: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 10,
  },
  filterScroll: {
    paddingHorizontal: 16,
    gap: 10,
    flexDirection: "row",
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.95)",
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 10,
    ...cardShadow,
  },
  filterChipOn: {
    backgroundColor: colors.ink,
  },
  filterLabel: { fontSize: 14, fontWeight: "700", color: colors.ink },
  filterLabelOn: { color: "#fff" },
  sheetScroll: {
    flex: 1,
    minHeight: 0,
  },
  sheetList: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  content: { paddingHorizontal: 16, paddingBottom: 48 },
  title: { fontSize: 24, fontWeight: "800", color: colors.ink, marginTop: 16 },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.bg,
    padding: 24,
  },
  meta: { marginTop: 8, fontSize: 14, color: colors.muted, lineHeight: 20 },
  actions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 8,
  },
  actionBtn: {
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  actionPrimary: {
    backgroundColor: colors.brand,
    borderColor: colors.brand,
  },
  actionText: { fontSize: 13, fontWeight: "600", color: colors.ink },
  actionPrimaryText: { fontSize: 13, fontWeight: "700", color: "#fff" },
  shareMsg: {
    marginTop: 0,
    marginBottom: 4,
    paddingHorizontal: 20,
    fontSize: 12,
    color: colors.ready,
  },
  section: { marginTop: 16 },
  mapPlaceholder: {
    height: 220,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  mapPlaceholderText: { fontSize: 12, color: colors.muted },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.ink,
    marginBottom: 10,
  },
  routeCard: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  routeCardOn: {
    borderColor: colors.brand,
    backgroundColor: colors.brandSoft,
  },
  routeTitle: { fontWeight: "700", color: colors.ink, fontSize: 15 },
  routeTheme: { marginTop: 2, fontSize: 12, color: colors.brand },
  routeTag: { marginTop: 4, fontSize: 12, color: colors.muted },
  routeOnHint: {
    marginTop: 8,
    fontSize: 11,
    fontWeight: "700",
    color: colors.brandHot,
  },
  dayTabs: { marginTop: 16, marginBottom: 8 },
  dayTab: {
    backgroundColor: colors.card,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: colors.line,
  },
  dayTabOn: { backgroundColor: colors.brand, borderColor: colors.brand },
  dayTabText: { fontSize: 13, fontWeight: "600", color: colors.ink },
  dayTabTextOn: { color: "#fff" },
  regen: { alignSelf: "flex-start", marginBottom: 10 },
  regenText: { color: colors.brand, fontWeight: "600", fontSize: 13 },
  summaryBox: {
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    marginBottom: 14,
  },
  summaryLabel: { fontSize: 12, color: colors.brand, fontWeight: "700" },
  summaryText: { marginTop: 4, fontSize: 14, color: colors.ink, lineHeight: 20 },
  item: {
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    marginBottom: 10,
  },
  itemCompact: {
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    marginBottom: 10,
  },
  feedCard: {
    backgroundColor: colors.card,
    borderRadius: 14,
    marginBottom: 12,
    overflow: "hidden",
  },
  feedRow: {
    flexDirection: "row",
    padding: 12,
    gap: 12,
  },
  feedThumbWrap: {
    width: 88,
    height: 88,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#eef2f7",
  },
  feedThumb: {
    width: 88,
    height: 88,
    borderRadius: 10,
  },
  feedThumbEmoji: {
    fontSize: 32,
    textAlign: "center",
    lineHeight: 88,
  },
  feedBody: { flex: 1, minWidth: 0 },
  feedTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.ink,
    lineHeight: 22,
  },
  feedTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 6,
    alignItems: "center",
  },
  feedTag: {
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  feedTagText: { fontSize: 11, fontWeight: "700" },
  feedTagMuted: {
    backgroundColor: "#f3f4f6",
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  feedTagMutedText: { fontSize: 11, color: colors.muted },
  feedDesc: {
    marginTop: 8,
    fontSize: 13,
    color: colors.muted,
    lineHeight: 19,
  },
  feedExpand: { color: colors.brand, fontWeight: "600" },
  feedMetaRow: { flexDirection: "row", gap: 10, marginTop: 8 },
  feedMeta: { fontSize: 12, color: colors.muted },
  feedRoute: { paddingHorizontal: 12, paddingBottom: 12 },
  itemDetailCta: {
    marginTop: 10,
    fontSize: 13,
    fontWeight: "700",
    color: colors.brandHot,
  },
  itemDescPreview: {
    marginTop: 6,
    fontSize: 13,
    color: colors.muted,
    lineHeight: 18,
  },
  itemOff: { opacity: 0.5 },
  itemHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  itemType: { fontSize: 12, color: colors.brand, fontWeight: "600" },
  itemAction: { fontSize: 12, color: colors.brandHot, fontWeight: "600" },
  itemName: { fontSize: 16, fontWeight: "700", color: colors.ink },
  itemDesc: { marginTop: 4, fontSize: 13, color: colors.muted, lineHeight: 18 },
  itemMetaRow: { flexDirection: "row", gap: 10, marginTop: 6 },
  itemMeta: { fontSize: 12, color: colors.muted },
  transport: { marginTop: 8, fontSize: 12, color: colors.muted },
  alts: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 10 },
  altsLabel: { fontSize: 12, color: colors.muted, alignSelf: "center" },
  altChip: {
    fontSize: 12,
    color: colors.brandHot,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: "hidden",
  },
  budget: {
    marginTop: 22,
    backgroundColor: colors.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
  },
  budgetRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  budgetLabel: { color: colors.muted, fontSize: 13 },
  budgetVal: { fontWeight: "600", color: colors.ink },
  budgetTotal: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
    paddingTop: 10,
    marginTop: 4,
    marginBottom: 0,
  },
  budgetHint: { fontSize: 12, color: colors.muted },
  budgetTotalVal: { fontSize: 22, fontWeight: "800", color: colors.brand },
  parallelRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: GRID_GAP,
  },
  parallelCol: {
    flex: 1,
    minWidth: 0,
  },
  parallelTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.ink,
    marginBottom: 8,
  },
  parallelHint: {
    fontSize: 11,
    color: colors.muted,
    marginBottom: 6,
    marginTop: -4,
  },
  parallelEmpty: {
    fontSize: 12,
    color: colors.muted,
    paddingVertical: 10,
  },
  compactCard: {
    backgroundColor: colors.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  compactSource: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.brand,
    marginBottom: 2,
  },
  compactTitle: {
    fontWeight: "700",
    color: colors.ink,
    fontSize: 13,
    lineHeight: 18,
  },
  compactAccent: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: "600",
    color: colors.ready,
  },
  generating: { marginTop: 16, fontSize: 16, fontWeight: "600", color: colors.ink },
  genRoot: {
    flex: 1,
    backgroundColor: "#eef2f7",
  },
  genMapWrap: {
    height: 280,
    backgroundColor: "#eef2f7",
    overflow: "hidden",
  },
  genBodyScroll: { flex: 1 },
  genBody: {
    paddingHorizontal: 16,
    paddingTop: 0,
    paddingBottom: 32,
  },
  genHero: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.ink,
    marginBottom: 12,
    paddingHorizontal: 20,
    marginTop: 4,
  },
  genPhaseRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingHorizontal: 20,
  },
  genPhaseItem: { flex: 1, alignItems: "center" },
  genPhaseDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.line,
    marginBottom: 4,
  },
  genPhaseDotDone: { backgroundColor: colors.brand },
  genPhaseDotActive: {
    backgroundColor: colors.brand,
    transform: [{ scale: 1.35 }],
  },
  genPhaseLabel: { fontSize: 9, color: colors.muted, textAlign: "center" },
  genPhaseLabelOn: { color: colors.brandHot, fontWeight: "700" },
  genStreamBubble: {
    backgroundColor: colors.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
    minHeight: 200,
  },
  genStreamRole: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.brand,
    marginBottom: 8,
  },
  genStreamStatus: {
    fontSize: 14,
    color: colors.muted,
    marginBottom: 12,
    lineHeight: 20,
  },
  genStreamScroll: { maxHeight: 320 },
  genStreamText: {
    fontSize: 15,
    color: colors.ink,
    lineHeight: 24,
  },
  genStreamTyping: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  genStreamTypingText: { fontSize: 13, color: colors.muted },
  genStreamCursor: {
    fontSize: 16,
    color: colors.brand,
    marginTop: 8,
    fontWeight: "300",
  },
  actionAi: {
    borderColor: colors.brand,
    backgroundColor: colors.brandSoft,
  },
  hint: { marginTop: 8, fontSize: 13, color: colors.muted, textAlign: "center" },
  error: { color: colors.danger, fontSize: 16, textAlign: "center" },
  retry: {
    marginTop: 16,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
  },
  retryText: { color: colors.brandHot, fontWeight: "700" },
});
