import { StyleSheet } from "react-native";
import { colors } from "../../theme";
import { GRID_GAP } from "./constants";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  content: { padding: 20, paddingBottom: 48 },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.bg,
    padding: 24,
  },
  title: { fontSize: 24, fontWeight: "800", color: colors.ink },
  meta: { marginTop: 8, fontSize: 14, color: colors.muted, lineHeight: 20 },
  actions: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 14 },
  actionBtn: {
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  actionPrimary: {
    backgroundColor: colors.brand,
    borderColor: colors.brand,
  },
  actionText: { fontSize: 13, fontWeight: "600", color: colors.ink },
  actionPrimaryText: { fontSize: 13, fontWeight: "700", color: "#fff" },
  shareMsg: { marginTop: 8, fontSize: 12, color: colors.ready },
  section: { marginTop: 22 },
  mapPlaceholder: {
    height: 220,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  mapPlaceholderText: { fontSize: 12, color: colors.muted },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.ink,
    marginBottom: 10,
  },
  routeCard: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  routeCardOn: {
    borderColor: colors.brand,
    backgroundColor: colors.brandSoft,
  },
  routeTitle: { fontWeight: "700", color: colors.ink, fontSize: 15 },
  routeTheme: { marginTop: 2, fontSize: 12, color: colors.brand },
  routeTag: { marginTop: 4, fontSize: 12, color: colors.muted },
  routeOnHint: {
    marginTop: 8,
    fontSize: 11,
    fontWeight: "700",
    color: colors.brandHot,
  },
  dayTabs: { marginTop: 16, marginBottom: 8 },
  dayTab: {
    backgroundColor: colors.card,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: colors.line,
  },
  dayTabOn: { backgroundColor: colors.brand, borderColor: colors.brand },
  dayTabText: { fontSize: 13, fontWeight: "600", color: colors.ink },
  dayTabTextOn: { color: "#fff" },
  regen: { alignSelf: "flex-start", marginBottom: 10 },
  regenText: { color: colors.brand, fontWeight: "600", fontSize: 13 },
  summaryBox: {
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    marginBottom: 14,
  },
  summaryLabel: { fontSize: 12, color: colors.brand, fontWeight: "700" },
  summaryText: { marginTop: 4, fontSize: 14, color: colors.ink, lineHeight: 20 },
  item: {
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 14,
    marginBottom: 10,
  },
  itemOff: { opacity: 0.5 },
  itemHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  itemType: { fontSize: 12, color: colors.brand, fontWeight: "600" },
  itemAction: { fontSize: 12, color: colors.brandHot, fontWeight: "600" },
  itemName: { fontSize: 16, fontWeight: "700", color: colors.ink },
  itemDesc: { marginTop: 4, fontSize: 13, color: colors.muted, lineHeight: 18 },
  itemMetaRow: { flexDirection: "row", gap: 10, marginTop: 6 },
  itemMeta: { fontSize: 12, color: colors.muted },
  transport: { marginTop: 8, fontSize: 12, color: colors.muted },
  alts: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 10 },
  altsLabel: { fontSize: 12, color: colors.muted, alignSelf: "center" },
  altChip: {
    fontSize: 12,
    color: colors.brandHot,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: "hidden",
  },
  budget: {
    marginTop: 22,
    backgroundColor: colors.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
  },
  budgetRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  budgetLabel: { color: colors.muted, fontSize: 13 },
  budgetVal: { fontWeight: "600", color: colors.ink },
  budgetTotal: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
    paddingTop: 10,
    marginTop: 4,
    marginBottom: 0,
  },
  budgetHint: { fontSize: 12, color: colors.muted },
  budgetTotalVal: { fontSize: 22, fontWeight: "800", color: colors.brand },
  parallelRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: GRID_GAP,
  },
  parallelCol: {
    flex: 1,
    minWidth: 0,
  },
  parallelTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.ink,
    marginBottom: 8,
  },
  parallelHint: {
    fontSize: 11,
    color: colors.muted,
    marginBottom: 6,
    marginTop: -4,
  },
  parallelEmpty: {
    fontSize: 12,
    color: colors.muted,
    paddingVertical: 10,
  },
  compactCard: {
    backgroundColor: colors.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  compactSource: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.brand,
    marginBottom: 2,
  },
  compactTitle: {
    fontWeight: "700",
    color: colors.ink,
    fontSize: 13,
    lineHeight: 18,
  },
  compactAccent: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: "600",
    color: colors.ready,
  },
  generating: { marginTop: 16, fontSize: 16, fontWeight: "600", color: colors.ink },
  hint: { marginTop: 8, fontSize: 13, color: colors.muted, textAlign: "center" },
  error: { color: colors.danger, fontSize: 16, textAlign: "center" },
  retry: {
    marginTop: 16,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
  },
  retryText: { color: colors.brandHot, fontWeight: "700" },
});
