import { StyleSheet } from "react-native";
import { colors } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  header: { flexDirection: "row", alignItems: "center", paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.line, backgroundColor: colors.card },
  backBtn: { paddingRight: 12, paddingVertical: 4 },
  backText: { fontSize: 16, color: colors.muted },
  headerTitle: { fontSize: 18, fontWeight: "800", color: colors.ink },
  body: { flex: 1, padding: 20 },
  centerTitle: { textAlign: "center", fontSize: 28, marginBottom: 8 },
  centerSub: { textAlign: "center", fontSize: 14, color: colors.muted, marginBottom: 28 },
  inputRow: { flexDirection: "row", alignItems: "center", marginBottom: 20 },
  inputWrap: { flex: 1 },
  input: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 12, fontSize: 16, color: colors.ink },
  modeBtn: { width: 44, height: 44, borderRadius: 22, borderWidth: 2, borderColor: colors.brand, backgroundColor: "#fff", alignItems: "center", justifyContent: "center", marginHorizontal: 10 },
  modeBtnText: { fontSize: 20 },
  modePopup: { position: "absolute", bottom: 54, left: "50%", transform: [{ translateX: -60 }], width: 120, backgroundColor: "#fff", borderRadius: 14, paddingVertical: 6, paddingHorizontal: 8, borderWidth: 1, borderColor: colors.line, shadowColor: "#000", shadowOpacity: 0.1, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: 6, zIndex: 100 },
  modeItem: { flexDirection: "row", alignItems: "center", paddingVertical: 8, paddingHorizontal: 8, borderRadius: 10 },
  modeItemOn: { backgroundColor: colors.brandSoft },
  modeItemEmoji: { fontSize: 16, width: 28 },
  modeItemText: { fontSize: 13, color: colors.ink, fontWeight: "600" },
  modeItemDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.brand, marginLeft: "auto" },
  suggestionPanel: { marginTop: 4, backgroundColor: colors.card, borderRadius: 14, borderWidth: 1, borderColor: colors.line, maxHeight: 280, flexDirection: "row" },
  suggestionScroll: { flex: 1 },
  suggestionGroup: { marginBottom: 6 },
  suggestionLetter: { fontSize: 13, fontWeight: "800", color: colors.brandHot, paddingHorizontal: 12, paddingTop: 8, paddingBottom: 4 },
  suggestionChips: { flexDirection: "row", flexWrap: "wrap", paddingHorizontal: 8 },
  suggestionChip: { paddingHorizontal: 10, paddingVertical: 6, margin: 3, borderRadius: 10, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.card },
  suggestionChipOn: { borderColor: colors.brand, backgroundColor: colors.brandSoft },
  suggestionChipText: { fontSize: 13, color: colors.ink },
  suggestionChipTextOn: { color: colors.brandHot, fontWeight: "600" },
  alphabetBar: { width: 22, alignItems: "center", justifyContent: "center", paddingVertical: 4, backgroundColor: colors.bg, borderLeftWidth: 1, borderLeftColor: colors.line, borderTopRightRadius: 14, borderBottomRightRadius: 14 },
  alphabetLetter: { fontSize: 10, fontWeight: "700", color: colors.muted, paddingVertical: 1 },
  alphabetLetterOn: { color: colors.brand, fontWeight: "800" },
  modeLabel: { fontSize: 14, fontWeight: "600", color: colors.ink, marginBottom: 10 },
  modeChips: { flexDirection: "row", gap: 8, marginBottom: 24 },
  modeChip: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.card },
  modeChipOn: { borderColor: colors.brand, backgroundColor: colors.brandSoft },
  modeChipText: { fontSize: 14, fontWeight: "600", color: colors.ink },
  modeChipTextOn: { color: colors.brandHot },
  searchBtn: { backgroundColor: colors.brand, borderRadius: 14, paddingVertical: 16, alignItems: "center", marginTop: 8 },
  searchBtnText: { color: "#fff", fontSize: 16, fontWeight: "700" },
  hint: { textAlign: "center", fontSize: 12, color: colors.muted, marginTop: 16 },
});
