import { Platform, StyleSheet } from "react-native";
import { cardShadow, colors } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  content: { padding: 20 },
  searchHint: {
    marginTop: 8,
    fontSize: 12,
    color: colors.muted,
  },
  modeLabel: {
    fontSize: 13,
    color: colors.muted,
    marginBottom: 8,
  },
  modeRow: { flexDirection: "row", gap: 10 },
  modeCard: {
    flex: 1,
    borderWidth: 2,
    borderColor: "transparent",
    borderRadius: 18,
    padding: 14,
    ...cardShadow,
  },
  modeCardOn: {
    borderColor: colors.brand,
  },
  modeTitle: { fontSize: 16, fontWeight: "800", color: colors.ink },
  modeTitleOn: { color: colors.brandHot },
  modeDesc: {
    marginTop: 4,
    fontSize: 12,
    color: colors.muted,
    lineHeight: 17,
  },
  quickCard: {
    marginTop: 14,
    borderRadius: 20,
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 14,
    ...cardShadow,
  },
  quickCardBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.92)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginBottom: 10,
  },
  quickCardBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.brand,
    marginRight: 6,
  },
  quickCardBadgeText: {
    fontSize: 12,
    color: colors.muted,
    fontWeight: "600",
  },
  quickCardTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.ink,
    lineHeight: 26,
  },
  quickCardTag: {
    marginTop: 4,
    marginBottom: 4,
    fontSize: 13,
    color: colors.muted,
    lineHeight: 18,
  },
  tipBlock: { marginTop: 12 },
  tipBlockTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.muted,
    marginBottom: 8,
  },
  tipRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 11,
    paddingHorizontal: 12,
    marginBottom: 8,
    borderRadius: 14,
    backgroundColor: colors.card,
  },
  tipTitle: { flex: 1, fontSize: 14, color: colors.ink, fontWeight: "600" },
  tipGo: {
    marginLeft: 8,
    fontSize: 13,
    color: colors.brandHot,
    fontWeight: "700",
  },
  note: {
    backgroundColor: colors.card,
    borderRadius: 14,
    padding: 12,
    marginTop: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.line,
  },
  noteText: { fontSize: 13, color: colors.ink, lineHeight: 18 },
  noteLink: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: "700",
    color: colors.brandHot,
  },
  label: { fontSize: 13, color: colors.muted, marginTop: 14, marginBottom: 6 },
  hint: { fontSize: 12, color: colors.muted, marginTop: 10, marginBottom: 4 },
  input: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.ink,
  },
  dateBtn: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dateBtnText: { fontSize: 16, color: colors.ink, fontWeight: "600" },
  dateBtnHint: { fontSize: 13, color: colors.brandHot, fontWeight: "600" },
  pickerWrap: {
    marginTop: 10,
    backgroundColor: "#fff",
    borderRadius: 14,
    borderWidth: 0,
    overflow: "hidden",
    paddingBottom: Platform.OS === "ios" ? 8 : 0,
  },
  pickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 4,
  },
  pickerTitle: { fontSize: 14, fontWeight: "600", color: colors.ink },
  pickerDone: { fontSize: 15, fontWeight: "700", color: colors.brandHot },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 4 },
  chip: {
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  chipOn: {
    borderColor: colors.brand,
    backgroundColor: colors.brandSoft,
  },
  chipText: { fontSize: 14, color: colors.ink, fontWeight: "600" },
  chipTextOn: { color: colors.brandHot, fontWeight: "700" },
  chipDesc: { fontSize: 11, color: colors.muted, marginTop: 2 },
  poiRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  poiSearchBlock: {
    marginTop: 10,
    position: "relative",
    zIndex: 30,
  },
  poiDropdown: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 56,
    zIndex: 40,
    elevation: 12,
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  poiDropdownScroll: { maxHeight: 200 },
  poiAdd: {
    backgroundColor: colors.brand,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    minWidth: 64,
    alignItems: "center",
  },
  poiAddText: { color: "#fff", fontWeight: "700" },
  poiItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  poiName: { fontSize: 14, fontWeight: "600", color: colors.ink },
  poiAddr: { fontSize: 12, color: colors.muted, marginTop: 2 },
  error: { marginTop: 14, color: colors.danger, fontSize: 14 },
  primaryBtn: {
    marginTop: 28,
    backgroundColor: colors.brand,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  btnDisabled: { opacity: 0.6 },
  primaryBtnText: { color: "#fff", fontSize: 16, fontWeight: "700" },
});
