import { StyleSheet } from "react-native";
import { cardShadow, colors } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  brand: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.ink,
    letterSpacing: 0.5,
  },
  headerActions: { flexDirection: "row", alignItems: "center" },
  headerLink: { marginLeft: 14 },
  genBtn: {
    backgroundColor: colors.brand,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
  },
  genBtnText: { color: "#fff", fontWeight: "700", fontSize: 14 },
  logout: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  pageTitle: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 12,
    fontSize: 28,
    fontWeight: "800",
    color: colors.ink,
    letterSpacing: 0.5,
  },
  banner: {
    marginHorizontal: 16,
    marginBottom: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.brandSoft,
    flexDirection: "row",
    alignItems: "center",
  },
  bannerText: {
    flex: 1,
    fontSize: 13,
    color: colors.ink,
    lineHeight: 18,
    marginRight: 10,
  },
  bannerLink: { fontSize: 13, fontWeight: "700", color: colors.brandHot },
  list: { paddingHorizontal: 16, paddingBottom: 32 },
  emptyWrap: { flexGrow: 1, justifyContent: "center", padding: 32 },
  emptyBox: { alignItems: "center" },
  empty: {
    textAlign: "center",
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 16,
  },
  emptyBtn: {
    backgroundColor: colors.brand,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
  },
  emptyBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  cardPress: { marginBottom: 14 },
  card: {
    borderRadius: 28,
    paddingTop: 16,
    paddingHorizontal: 18,
    paddingBottom: 18,
    minHeight: 188,
    overflow: "hidden",
    ...cardShadow,
  },
  badge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.92)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginBottom: 12,
  },
  badgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.brand,
    marginRight: 6,
  },
  badgeDotLive: { backgroundColor: "#2e7d32" },
  badgeDotBusy: { backgroundColor: "#ef6c00" },
  badgeDotFail: { backgroundColor: "#c62828" },
  badgeDotSoon: { backgroundColor: colors.brand },
  badgeText: {
    fontSize: 12,
    color: colors.muted,
    fontWeight: "600",
    lineHeight: 16,
  },
  cardTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: colors.ink,
    lineHeight: 32,
    maxWidth: "72%",
    marginBottom: 12,
  },
  metaBlock: {
    flexDirection: "row",
    alignItems: "stretch",
    maxWidth: "68%",
    marginBottom: 18,
  },
  metaBar: {
    width: 2,
    borderRadius: 1,
    backgroundColor: "rgba(255,109,0,0.28)",
    marginRight: 10,
  },
  metaTextCol: { flex: 1 },
  metaLine: {
    fontSize: 13,
    color: colors.muted,
    lineHeight: 20,
  },
  cardBottom: {
    marginTop: "auto",
    flexDirection: "row",
    alignItems: "center",
    minHeight: 40,
  },
  avatars: { flexDirection: "row", alignItems: "center" },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.9)",
  },
  avatarPrimary: { backgroundColor: colors.brand },
  avatarSecondary: { backgroundColor: "#E07A3A" },
  avatarText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 16,
  },
  coverWrap: {
    position: "absolute",
    right: -6,
    bottom: -18,
    width: 132,
    height: 132,
    transform: [{ rotate: "14deg" }],
  },
  cover: {
    width: "100%",
    height: "100%",
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.35)",
  },
  center: { padding: 32, alignItems: "center" },
  error: { color: colors.danger, textAlign: "center", fontSize: 15 },
  hint: {
    marginTop: 8,
    fontSize: 12,
    color: colors.muted,
    textAlign: "center",
  },
  retry: {
    marginTop: 16,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
  },
  retryText: { color: colors.brandHot, fontWeight: "700" },
});
