import { StyleSheet } from "react-native";
import { cardShadow, colors } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  topBar: {
    paddingHorizontal: 20,
    paddingBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  logo: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.ink,
    letterSpacing: 1,
    flexShrink: 0,
    marginRight: 12,
  },
  topActions: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 1,
    flexWrap: "nowrap",
  },
  topActionItem: { marginLeft: 14, flexShrink: 0 },
  topLink: {
    fontSize: 14,
    color: colors.ink,
    fontWeight: "600",
    lineHeight: 20,
  },
  topMuted: { fontSize: 13, color: colors.muted, lineHeight: 20 },
  topCta: {
    fontSize: 14,
    color: colors.brand,
    fontWeight: "700",
    lineHeight: 20,
  },
  hero: {
    height: 320,
    backgroundColor: "#1a1a1a",
    overflow: "hidden",
  },
  heroPage: {
    height: 320,
    overflow: "hidden",
    backgroundColor: "#1a1a1a",
  },
  heroImg: {
    position: "absolute",
    top: 0,
    left: 0,
    height: 320,
    transform: [{ scale: 1.06 }],
  },
  heroMask: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(0,0,0,0.38)",
  },
  heroText: {
    position: "absolute",
    left: 20,
    right: 20,
    bottom: 44,
  },
  heroEyebrow: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 12,
    letterSpacing: 2,
    marginBottom: 8,
    lineHeight: 18,
  },
  heroTitle: {
    color: "#fff",
    fontSize: 26,
    fontWeight: "800",
    lineHeight: 36,
    marginBottom: 8,
  },
  heroSub: {
    color: "rgba(255,255,255,0.88)",
    fontSize: 14,
    lineHeight: 22,
  },
  dots: {
    position: "absolute",
    left: 20,
    bottom: 14,
    flexDirection: "row",
  },
  searchWrap: {
    marginTop: 16,
    marginHorizontal: 20,
  },
  searchBox: {
    width: "100%",
    height: 52,
    backgroundColor: colors.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    flexDirection: "row",
    alignItems: "stretch",
    overflow: "hidden",
  },
  searchInput: {
    flex: 1,
    height: "100%",
    paddingHorizontal: 16,
    fontSize: 15,
    color: colors.ink,
  },
  searchBtn: {
    height: "100%",
    backgroundColor: colors.brand,
    paddingHorizontal: 22,
    justifyContent: "center",
    alignItems: "center",
  },
  searchBtnText: { color: "#fff", fontWeight: "700", fontSize: 14 },
  cityPanel: {
    marginTop: 10,
    backgroundColor: colors.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 12,
    maxHeight: 280,
  },
  cityPanelTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.muted,
    marginBottom: 8,
  },
  cityScroll: { maxHeight: 320 },
  cityEmpty: { fontSize: 13, color: colors.muted, paddingVertical: 8 },
  cityGroup: { marginBottom: 10 },
  cityLetter: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.brandHot,
    marginBottom: 6,
  },
  cityChips: { flexDirection: "row", flexWrap: "wrap", marginHorizontal: -4 },
  cityChip: {
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 7,
    margin: 4,
  },
  cityChipOn: {
    borderColor: colors.brand,
    backgroundColor: colors.brandSoft,
  },
  cityChipText: {
    fontSize: 14,
    color: colors.ink,
    fontWeight: "600",
    lineHeight: 20,
  },
  cityChipTextOn: { color: colors.brandHot },
  shortcuts: {
    marginTop: 16,
    marginHorizontal: 15,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  shortcut: {
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    margin: 5,
    minHeight: 72,
    ...cardShadow,
  },
  shortcutTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.ink,
    lineHeight: 22,
  },
  shortcutDesc: {
    marginTop: 4,
    fontSize: 12,
    color: colors.muted,
    lineHeight: 18,
  },
  section: { marginTop: 28, paddingHorizontal: 16 },
  sectionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.ink,
    marginBottom: 12,
    lineHeight: 26,
    paddingHorizontal: 4,
  },
  sectionLink: {
    fontSize: 13,
    color: colors.brand,
    fontWeight: "600",
    marginBottom: 12,
    lineHeight: 20,
  },
  chips: { flexDirection: "row", flexWrap: "wrap", marginHorizontal: -2 },
  chip: {
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 9,
    margin: 4,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
  },
  chipText: {
    fontSize: 14,
    color: colors.ink,
    fontWeight: "600",
    lineHeight: 20,
  },
  destGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  destCardPress: { marginBottom: 10 },
  destCard: {
    borderRadius: 20,
    paddingTop: 12,
    paddingLeft: 12,
    paddingRight: 10,
    paddingBottom: 12,
    minHeight: 108,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "stretch",
    ...cardShadow,
  },
  destLeft: {
    flex: 1,
    paddingRight: 4,
    zIndex: 2,
    justifyContent: "center",
  },
  destTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: colors.ink,
    lineHeight: 24,
    marginBottom: 4,
  },
  destMeta: {
    fontSize: 11,
    color: colors.muted,
    lineHeight: 16,
  },
  destCoverWrap: {
    width: 56,
    justifyContent: "flex-end",
    alignItems: "flex-end",
    zIndex: 1,
  },
  destCoverInner: {
    width: 52,
    height: 52,
    borderRadius: 12,
    overflow: "hidden",
    transform: [{ rotate: "10deg" }],
    marginRight: 0,
    marginBottom: 2,
    backgroundColor: "rgba(255,255,255,0.35)",
  },
  destCover: {
    width: "100%",
    height: "100%",
  },
  bigCta: {
    marginTop: 20,
    marginHorizontal: 16,
    backgroundColor: colors.ink,
    borderRadius: 22,
    paddingVertical: 22,
    paddingHorizontal: 20,
  },
  bigCtaTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 26,
  },
  bigCtaSub: {
    color: "rgba(255,255,255,0.65)",
    marginTop: 6,
    fontSize: 13,
    lineHeight: 20,
  },
  llmBar: {
    marginTop: 18,
    marginHorizontal: 20,
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
    flexDirection: "row",
    alignItems: "center",
  },
  llmDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.brand,
    marginRight: 10,
  },
  llmMsg: { fontSize: 13, color: colors.ink, fontWeight: "600", lineHeight: 20 },
  llmUrl: { marginTop: 2, fontSize: 11, color: colors.muted, lineHeight: 16 },
});
