import { StyleSheet } from "react-native";
import { colors } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  center: { alignItems: "center", justifyContent: "center" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  back: { fontSize: 16, color: colors.brandHot, fontWeight: "700" },
  editBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: colors.brandSoft,
    borderWidth: 1,
    borderColor: colors.brand,
  },
  editBtnIcon: { fontSize: 13, color: colors.brandHot, fontWeight: "700" },
  editBtnText: { fontSize: 13, color: colors.brandHot, fontWeight: "800" },
  scroll: { paddingHorizontal: 20, paddingBottom: 40 },
  emoji: { fontSize: 40, marginTop: 8 },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: colors.ink,
    marginTop: 8,
    lineHeight: 34,
  },
  author: { marginTop: 6, fontSize: 13, color: colors.muted },
  summary: {
    marginTop: 12,
    fontSize: 15,
    color: colors.ink,
    lineHeight: 22,
  },
  meta: {
    marginTop: 10,
    fontSize: 12,
    color: colors.muted,
    alignSelf: "flex-end",
  },
  subBtn: {
    marginTop: 18,
    backgroundColor: colors.ink,
    borderRadius: 24,
    borderCurve: "continuous",
    paddingVertical: 13,
    alignItems: "center",
  },
  subBtnOn: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
  },
  subBtnText: { color: "#fff", fontSize: 15, fontWeight: "800" },
  subBtnTextOn: { color: colors.muted },
  sectionTitle: {
    marginTop: 28,
    marginBottom: 12,
    fontSize: 17,
    fontWeight: "800",
    color: colors.ink,
  },
  placeRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
    gap: 12,
  },
  placeThumb: {
    width: 56,
    height: 56,
    borderRadius: 14,
    borderCurve: "continuous",
    overflow: "hidden",
    backgroundColor: colors.brandSoft,
  },
  placeThumbImg: { width: "100%", height: "100%" },
  placeBody: { flex: 1, minWidth: 0 },
  placeName: { fontSize: 16, fontWeight: "700", color: colors.ink },
  placeNote: { marginTop: 4, fontSize: 13, color: colors.ink, lineHeight: 19 },
  placeSub: { marginTop: 4, fontSize: 12, color: colors.muted, lineHeight: 17 },
});
