import { StyleSheet } from "react-native";
import { colors } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  center: { alignItems: "center", justifyContent: "center" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  back: { fontSize: 16, color: colors.brandHot, fontWeight: "700" },
  ownerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  deleteBtn: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: "#FFF0F0",
    borderWidth: 1,
    borderColor: "#FFC7C7",
  },
  deleteBtnText: { fontSize: 13, color: colors.danger, fontWeight: "800" },
  editBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: colors.brandSoft,
    borderWidth: 1,
    borderColor: colors.brand,
  },
  editBtnIcon: { fontSize: 13, color: colors.brandHot, fontWeight: "700" },
  editBtnText: { fontSize: 13, color: colors.brandHot, fontWeight: "800" },
  scroll: { paddingHorizontal: 20, paddingBottom: 40 },
  emoji: { fontSize: 40, marginTop: 8 },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: colors.ink,
    marginTop: 8,
    lineHeight: 34,
  },
  authorRow: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  author: { fontSize: 13, color: colors.muted },
  authorLink: { color: colors.brandHot, fontWeight: "700" },
  summary: {
    marginTop: 12,
    fontSize: 15,
    color: colors.ink,
    lineHeight: 22,
  },
  meta: {
    marginTop: 10,
    fontSize: 12,
    color: colors.muted,
    alignSelf: "flex-end",
  },
  subBtn: {
    marginTop: 18,
    backgroundColor: colors.ink,
    borderRadius: 24,
    borderCurve: "continuous",
    paddingVertical: 13,
    alignItems: "center",
  },
  subBtnOn: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
  },
  subBtnText: { color: "#fff", fontSize: 15, fontWeight: "800" },
  subBtnTextOn: { color: colors.muted },
  sectionTitle: {
    marginTop: 28,
    marginBottom: 12,
    fontSize: 17,
    fontWeight: "800",
    color: colors.ink,
  },
  placeRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
    gap: 12,
  },
  placeThumb: {
    width: 56,
    height: 56,
    borderRadius: 14,
    borderCurve: "continuous",
    overflow: "hidden",
    backgroundColor: colors.brandSoft,
  },
  placeThumbImg: { width: "100%", height: "100%" },
  placeBody: { flex: 1, minWidth: 0 },
  placeName: { fontSize: 16, fontWeight: "700", color: colors.ink },
  placeNote: { marginTop: 4, fontSize: 13, color: colors.ink, lineHeight: 19 },
  placeSub: { marginTop: 4, fontSize: 12, color: colors.muted, lineHeight: 17 },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 14,
  },
  likeBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 16,
    height: 46,
    borderRadius: 23,
    borderCurve: "continuous",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
  },
  likeBtnOn: { backgroundColor: "#fff0f0", borderColor: "#ffb3b3" },
  likeIcon: { fontSize: 18, color: colors.muted },
  likeIconOn: { color: "#e5484d" },
  likeText: { fontSize: 15, fontWeight: "800", color: colors.ink },
  likeTextOn: { color: "#e5484d" },
  subBtnFlex: { flex: 1 },
  commentRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
  },
  commentBody: { flex: 1, minWidth: 0 },
  commentName: { fontSize: 13, fontWeight: "700", color: colors.muted },
  commentContent: { marginTop: 3, fontSize: 14, color: colors.ink, lineHeight: 20 },
  commentTime: { marginTop: 4, fontSize: 11, color: colors.muted },
  commentDel: { fontSize: 12, color: colors.danger, fontWeight: "700", padding: 4 },
  commentInputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
    marginTop: 12,
  },
  flex: { flex: 1 },
  commentFooter: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: colors.card,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.line,
  },
  commentInput: {
    flex: 1,
    minHeight: 44,
    maxHeight: 110,
    backgroundColor: colors.bgSurface,
    borderRadius: 14,
    borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 12,
    fontSize: 14,
    color: colors.ink,
  },
  commentSend: {
    height: 44,
    paddingHorizontal: 18,
    borderRadius: 22,
    borderCurve: "continuous",
    backgroundColor: colors.ink,
    alignItems: "center",
    justifyContent: "center",
  },
  commentSendText: { color: "#fff", fontSize: 14, fontWeight: "800" },
  commentEmpty: { marginTop: 8, fontSize: 13, color: colors.muted },
});
