import { StyleSheet } from "react-native";
import { colors, cardShadow } from "../../theme";

export const styles = StyleSheet.create({
  mapRoot: { flex: 1, backgroundColor: "#EFE8F8" },
  center: { alignItems: "center", justifyContent: "center" },
  mapBox: { ...StyleSheet.absoluteFillObject, backgroundColor: "#EFE8F8" },
  map: { flex: 1, backgroundColor: "#EFE8F8" },
  topBar: {
    position: "absolute",
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    zIndex: 4,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.94)",
    alignItems: "center",
    justifyContent: "center",
    ...cardShadow,
  },
  backBtnText: { fontSize: 22, color: colors.ink, fontWeight: "300", marginTop: -2 },
  topTitle: { fontSize: 16, fontWeight: "800", color: colors.ink },
  locateBtn: {
    position: "absolute",
    right: 14,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.94)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 4,
    ...cardShadow,
  },
  sheetScroll: { flex: 1, minHeight: 0, paddingHorizontal: 20 },
  label: {
    marginTop: 12,
    marginBottom: 6,
    fontSize: 13,
    fontWeight: "700",
    color: colors.ink,
  },
  input: {
    backgroundColor: colors.bgSurface,
    borderRadius: 14,
    borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: colors.ink,
  },
  inputMulti: { minHeight: 72, textAlignVertical: "top" },
  emojiRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  emojiChip: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderCurve: "continuous",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.bgSurface,
  },
  emojiChipOn: { backgroundColor: colors.brandSoft, borderWidth: 1, borderColor: colors.brand },
  emojiText: { fontSize: 20 },
  placeHead: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  link: { fontSize: 13, color: colors.brandHot, fontWeight: "700" },
  searchField: {
    marginTop: 8,
    height: 44,
    borderRadius: 14,
    borderCurve: "continuous",
    backgroundColor: colors.bgSurface,
    paddingHorizontal: 12,
    justifyContent: "center",
  },
  searchInput: { fontSize: 15, color: colors.ink, padding: 0 },
  resultsBox: {
    marginTop: 6,
    borderRadius: 14,
    borderCurve: "continuous",
    backgroundColor: colors.bgSurface,
    overflow: "hidden",
    maxHeight: 180,
  },
  searchRow: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
  },
  searchName: { fontSize: 15, fontWeight: "700", color: colors.ink },
  searchSub: { marginTop: 2, fontSize: 12, color: colors.muted },
  placeRow: {
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
  },
  placeRowActive: {
    backgroundColor: colors.brandSoft,
    borderRadius: 12,
    borderCurve: "continuous",
    paddingHorizontal: 8,
  },
  placeMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  placeRowTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  placeThumb: {
    width: 48,
    height: 48,
    borderRadius: 12,
    borderCurve: "continuous",
    overflow: "hidden",
    backgroundColor: colors.brandSoft,
  },
  placeThumbImg: { width: "100%", height: "100%" },
  placeBody: { flex: 1, minWidth: 0 },
  placeName: { fontSize: 14, fontWeight: "700", color: colors.ink },
  placeSub: { marginTop: 2, fontSize: 11, color: colors.muted },
  placeNoteInput: {
    marginTop: 8,
    marginBottom: 4,
    backgroundColor: "#fff",
    borderRadius: 10,
    borderCurve: "continuous",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.line,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    color: colors.ink,
    minHeight: 38,
    textAlignVertical: "top",
  },
  removeBtn: { padding: 4 },
  remove: { fontSize: 16, color: colors.muted },
  publishBtn: {
    marginHorizontal: 48,
    marginTop: 4,
    marginBottom: 8,
    height: 52,
    borderRadius: 26,
    borderCurve: "continuous",
    backgroundColor: colors.ink,
    alignItems: "center",
    justifyContent: "center",
    ...cardShadow,
  },
  publishBtnDisabled: { opacity: 0.6 },
  publishText: { color: "#fff", fontSize: 16, fontWeight: "800" },
});
