import { StyleSheet } from "react-native";
import { colors, cardShadow } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  topBar: {
    paddingHorizontal: 20,
    paddingBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  logo: { fontSize: 22, fontWeight: "800", color: colors.ink, letterSpacing: 1 },
  topActions: { flexDirection: "row", alignItems: "center" },
  topActionItem: { marginLeft: 14 },
  topLink: { fontSize: 14, color: colors.ink, fontWeight: "600" },
  topCta: { fontSize: 14, color: colors.brand, fontWeight: "700" },
  hero: { height: 280, backgroundColor: "#eef2f7", overflow: "hidden" },
  heroMapBox: { flex: 1, position: "relative" },
  heroLocBar: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 12,
  },
  heroLocChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.94)",
    borderRadius: 26, borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 10,
    ...cardShadow,
  },
  heroLocIcon: { fontSize: 22, marginRight: 10 },
  heroLocTextWrap: { flex: 1, minWidth: 0 },
  heroLocTitle: { fontSize: 15, fontWeight: "800", color: colors.ink },
  heroLocMeta: { fontSize: 12, color: colors.muted, marginTop: 2 },
  heroLocArrow: { fontSize: 20, color: colors.brand, fontWeight: "300", marginLeft: 8 },
  heroLocHint: {
    flex: 1,
    fontSize: 13,
    color: colors.muted,
    lineHeight: 18,
    marginLeft: 4,
  },
  heroMapControls: {
    position: "absolute",
    right: 10,
    top: 10,
    gap: 6,
  },
  heroMapExpand: {
    position: "absolute",
    right: 10,
    bottom: 72,
    backgroundColor: "rgba(0,0,0,0.55)",
    borderRadius: 24, borderCurve: "continuous",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  searchWrap: { marginTop: 14, marginHorizontal: 20 },
  searchBox: {
    width: "100%", height: 48, backgroundColor: colors.card, borderRadius: 24, borderCurve: "continuous",
    borderWidth: 1, borderColor: colors.line, flexDirection: "row",
    alignItems: "stretch", overflow: "hidden",
  },
  searchInput: { flex: 1, height: "100%", paddingHorizontal: 16, fontSize: 15, color: colors.ink },
  searchBtn: { height: "100%", backgroundColor: colors.brand, paddingHorizontal: 22, justifyContent: "center" },
  searchBtnText: { color: "#fff", fontWeight: "700", fontSize: 14 },
  cityPanel: {
    marginTop: 8, backgroundColor: colors.card, borderRadius: 24, borderCurve: "continuous",
    borderWidth: 1, borderColor: colors.line, padding: 12, maxHeight: 260,
  },
  cityPanelTitle: { fontSize: 12, fontWeight: "700", color: colors.muted, marginBottom: 8 },
  cityScroll: { maxHeight: 300 },
  cityEmpty: { fontSize: 13, color: colors.muted, paddingVertical: 8 },
  cityGroup: { marginBottom: 10 },
  cityLetter: { fontSize: 13, fontWeight: "800", color: colors.brandHot, marginBottom: 6 },
  cityChips: { flexDirection: "row", flexWrap: "wrap", marginHorizontal: -4 },
  cityChip: {
    borderWidth: 1, borderColor: colors.line, backgroundColor: colors.card,
    borderRadius: 22, borderCurve: "continuous", paddingHorizontal: 12, paddingVertical: 7, margin: 4,
  },
  cityChipOn: { borderColor: colors.brand, backgroundColor: colors.brandSoft },
  cityChipText: { fontSize: 14, color: colors.ink, fontWeight: "600", lineHeight: 20 },
  cityChipTextOn: { color: colors.brandHot },
  shortcuts: { marginTop: 14, marginHorizontal: 15, flexDirection: "row", flexWrap: "wrap" },
  shortcut: {
    borderRadius: 28, borderCurve: "continuous", paddingHorizontal: 14, paddingVertical: 14, margin: 5,
    minHeight: 72, ...cardShadow,
  },
  shortcutTitle: { fontSize: 15, fontWeight: "800", color: colors.ink, lineHeight: 22 },
  shortcutDesc: { marginTop: 4, fontSize: 12, color: colors.muted, lineHeight: 18 },
  section: { marginTop: 24, paddingHorizontal: 16 },
  sectionRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12, paddingHorizontal: 4 },
  sectionTitle: { fontSize: 18, fontWeight: "800", color: colors.ink, marginBottom: 12, lineHeight: 26, paddingHorizontal: 4 },
  sectionLink: { fontSize: 13, color: colors.brand, fontWeight: "600", marginBottom: 12, lineHeight: 20 },
  chips: { flexDirection: "row", flexWrap: "wrap", marginHorizontal: -2 },
  chip: {
    borderRadius: 30, borderCurve: "continuous", paddingHorizontal: 14, paddingVertical: 9, margin: 4,
    backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line,
  },
  chipText: { fontSize: 14, color: colors.ink, fontWeight: "600", lineHeight: 20 },
  destGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between" },
  destCardPress: { marginBottom: 10 },
  destCard: {
    borderRadius: 30, borderCurve: "continuous", paddingTop: 12, paddingLeft: 12, paddingRight: 10, paddingBottom: 12,
    minHeight: 100, overflow: "hidden", flexDirection: "row", alignItems: "stretch", ...cardShadow,
  },
  destLeft: { flex: 1, paddingRight: 4, zIndex: 2, justifyContent: "center" },
  destTitle: { fontSize: 17, fontWeight: "800", color: colors.ink, lineHeight: 24, marginBottom: 4 },
  destMeta: { fontSize: 11, color: colors.muted, lineHeight: 16 },
  destCoverWrap: { width: 56, justifyContent: "flex-end", alignItems: "flex-end", zIndex: 1 },
  destCoverInner: {
    width: 52, height: 52, borderRadius: 22, borderCurve: "continuous", overflow: "hidden",
    transform: [{ rotate: "10deg" }], marginRight: 0, marginBottom: 2,
    backgroundColor: "rgba(255,255,255,0.35)",
  },
  destCover: { width: "100%", height: "100%" },
  mapLoading: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  mapTapText: { color: "#fff", fontSize: 11, fontWeight: "700" },
  mapCtrlBtn: {
    width: 36,
    height: 36,
    borderRadius: 28, borderCurve: "continuous",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.line,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  mapCtrlText: { fontSize: 18, fontWeight: "700", color: colors.ink, lineHeight: 20 },
  mapLocateBtn: { marginTop: 2 },
  mapLocateText: { fontSize: 10, fontWeight: "800", color: "#1a66ff" },
});
