import { StyleSheet } from "react-native";
import { colors, cardShadow } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "transparent" },
  map: { ...StyleSheet.absoluteFillObject },

  topOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 8,
    zIndex: 20,
  },
  topAvatar: {
    ...cardShadow,
  },
  topSettingsBtn: {
    width: 40,
    height: 40,
    borderRadius: 30,
    borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.92)",
    alignItems: "center",
    justifyContent: "center",
    ...cardShadow,
  },
  mapControls: {
    position: "absolute",
    right: 16,
    zIndex: 12,
    gap: 8,
  },
  mapCtrlBtn: {
    width: 40,
    height: 40,
    borderRadius: 30,
    borderCurve: "continuous",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.line,
    ...cardShadow,
  },

  sheetHead: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    marginTop: 4,
    marginBottom: 12,
    gap: 10,
  },
  sheetTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 22,
    fontWeight: "800",
    color: colors.ink,
  },
  sheetDesc: {
    fontSize: 13,
    color: colors.muted,
    lineHeight: 20,
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  nearbyBubble: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 0,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 30,
    borderCurve: "continuous",
    backgroundColor: "#E8F4FC",
  },
  nearbyBubbleText: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.brandHot,
    lineHeight: 18,
  },
  nearbyBubbleArrow: {
    fontSize: 15,
    color: colors.brandHot,
    fontWeight: "300",
    marginLeft: 2,
    marginTop: -1,
  },
  sheetScroll: {
    flex: 1,
    minHeight: 0,
  },
  sheetContent: {
    flex: 1,
    minHeight: 0,
  },
  sheetScrollContent: {
    paddingBottom: 16,
  },

  searchWrap: { marginTop: 4, marginHorizontal: 20 },
  searchBox: {
    width: "100%",
    height: 48,
    backgroundColor: colors.card,
    borderRadius: 24,
    borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    flexDirection: "row",
    alignItems: "stretch",
    overflow: "hidden",
  },
  searchInput: {
    flex: 1,
    height: "100%",
    paddingHorizontal: 16,
    fontSize: 15,
    color: colors.ink,
  },
  searchBtn: {
    height: "100%",
    backgroundColor: colors.brand,
    paddingHorizontal: 22,
    justifyContent: "center",
  },
  searchBtnText: { color: "#fff", fontWeight: "700", fontSize: 14 },
  cityPanel: {
    marginTop: 8,
    backgroundColor: colors.card,
    borderRadius: 24,
    borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    padding: 12,
    maxHeight: 260,
  },
  cityPanelTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.muted,
    marginBottom: 8,
  },
  cityScroll: { maxHeight: 300 },
  cityEmpty: { fontSize: 13, color: colors.muted, paddingVertical: 8 },
  cityGroup: { marginBottom: 10 },
  cityLetter: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.brandHot,
    marginBottom: 6,
  },
  cityChips: { flexDirection: "row", flexWrap: "wrap", marginHorizontal: -4 },
  cityChip: {
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    borderRadius: 22,
    borderCurve: "continuous",
    paddingHorizontal: 12,
    paddingVertical: 7,
    margin: 4,
  },
  cityChipOn: { borderColor: colors.brand, backgroundColor: colors.brandSoft },
  cityChipText: {
    fontSize: 14,
    color: colors.ink,
    fontWeight: "600",
    lineHeight: 20,
  },
  cityChipTextOn: { color: colors.brandHot },
  shortcuts: {
    marginTop: 14,
    marginHorizontal: 15,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  shortcut: {
    borderRadius: 28,
    borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 14,
    margin: 5,
    minHeight: 72,
    ...cardShadow,
  },
  shortcutTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.ink,
    lineHeight: 22,
  },
  shortcutDesc: {
    marginTop: 4,
    fontSize: 12,
    color: colors.muted,
    lineHeight: 18,
  },
  section: { marginTop: 20, paddingHorizontal: 16 },
  sectionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.ink,
    marginBottom: 12,
    lineHeight: 26,
    paddingHorizontal: 4,
  },
  sectionLink: {
    fontSize: 13,
    color: colors.brand,
    fontWeight: "600",
    marginBottom: 12,
    lineHeight: 20,
  },
  chips: { flexDirection: "row", flexWrap: "wrap", marginHorizontal: -2 },
  chip: {
    borderRadius: 30,
    borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 9,
    margin: 4,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
  },
  chipText: {
    fontSize: 14,
    color: colors.ink,
    fontWeight: "600",
    lineHeight: 20,
  },
  destGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  destCardPress: { marginBottom: 10 },
  destCard: {
    borderRadius: 30,
    borderCurve: "continuous",
    paddingTop: 12,
    paddingLeft: 12,
    paddingRight: 10,
    paddingBottom: 12,
    minHeight: 100,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "stretch",
    ...cardShadow,
  },
  destLeft: { flex: 1, paddingRight: 4, zIndex: 2, justifyContent: "center" },
  destTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: colors.ink,
    lineHeight: 24,
    marginBottom: 4,
  },
  destMeta: { fontSize: 11, color: colors.muted, lineHeight: 16 },
  destCoverWrap: {
    width: 56,
    justifyContent: "flex-end",
    alignItems: "flex-end",
    zIndex: 1,
  },
  destCoverInner: {
    width: 52,
    height: 52,
    borderRadius: 22,
    borderCurve: "continuous",
    overflow: "hidden",
    transform: [{ rotate: "10deg" }],
    marginRight: 0,
    marginBottom: 2,
    backgroundColor: "rgba(255,255,255,0.35)",
  },
  destCover: { width: "100%", height: "100%" },
  collectionHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    gap: 8,
  },
  sharePlanBtn: {
    flexShrink: 0,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderCurve: "continuous",
    backgroundColor: colors.brandSoft,
    borderWidth: 1,
    borderColor: colors.brand,
  },
  sharePlanText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.brandHot,
  },
  mapLoading: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.bg,
    zIndex: 5,
  },
  mapHidden: { opacity: 0 },
  mapErrorText: {
    fontSize: 14,
    color: colors.muted,
    textAlign: "center",
    paddingHorizontal: 32,
    lineHeight: 20,
  },
  mapRetryBtn: {
    marginTop: 14,
    backgroundColor: colors.brand,
    borderRadius: 22,
    borderCurve: "continuous",
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  mapRetryText: { color: "#fff", fontWeight: "700", fontSize: 14 },
});
