import { StyleSheet } from "react-native";
import { colors, cardShadow } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  back: { fontSize: 16, color: colors.brandHot, fontWeight: "700" },
  title: { fontSize: 16, fontWeight: "800", color: colors.ink },
  headerSpacer: { width: 48 },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },
  scroll: { paddingHorizontal: 20, paddingBottom: 32 },
  profileCard: {
    marginTop: 8,
    backgroundColor: colors.card,
    borderRadius: 22,
    borderCurve: "continuous",
    padding: 20,
    alignItems: "center",
    ...cardShadow,
  },
  username: { marginTop: 12, fontSize: 20, fontWeight: "800", color: colors.ink },
  roleTag: {
    marginTop: 6,
    backgroundColor: colors.brandSoft,
    borderRadius: 10,
    borderCurve: "continuous",
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  roleTagText: { fontSize: 11, color: colors.brandHot, fontWeight: "700" },
  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
    gap: 0,
  },
  statItem: { alignItems: "center", paddingHorizontal: 18 },
  statNum: { fontSize: 18, fontWeight: "800", color: colors.ink },
  statLabel: { marginTop: 2, fontSize: 12, color: colors.muted },
  statDivider: { width: StyleSheet.hairlineWidth, height: 28, backgroundColor: colors.line },
  followBtn: {
    marginTop: 18,
    minWidth: 132,
    height: 42,
    borderRadius: 21,
    borderCurve: "continuous",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  followBtnOn: { backgroundColor: colors.brand },
  followBtnOff: { backgroundColor: colors.bgSurface, borderWidth: 1, borderColor: colors.line },
  followText: { fontSize: 15, fontWeight: "800", color: "#fff" },
  followTextOff: { color: colors.ink },
  selfText: { marginTop: 18, fontSize: 14, color: colors.muted },
  sectionTitle: {
    marginTop: 22,
    marginBottom: 12,
    fontSize: 15,
    fontWeight: "800",
    color: colors.ink,
  },
  empty: {
    marginTop: 24,
    textAlign: "center",
    fontSize: 14,
    color: colors.muted,
  },
});
