import { StyleSheet } from "react-native";
import { colors, cardShadow } from "../../theme";

export const styles = StyleSheet.create({
  root: {
    backgroundColor: "#eef2f7",
    overflow: "hidden",
  },
  rootFill: { ...StyleSheet.absoluteFill },
  mapBox: { flex: 1, position: "relative" },
  mapBoxFill: { ...StyleSheet.absoluteFill },
  mapLoading: {
    ...StyleSheet.absoluteFill,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#eef2f7",
  },
  mapHint: { fontSize: 14, color: colors.muted, textAlign: "center", padding: 20 },
  statusBar: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 12,
  },
  statusChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.94)",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    ...cardShadow,
  },
  statusIcon: { fontSize: 20, marginRight: 10 },
  statusTextWrap: { flex: 1, minWidth: 0 },
  statusTitle: { fontSize: 15, fontWeight: "800", color: colors.ink },
  statusSub: { fontSize: 12, color: colors.muted, marginTop: 2 },
  mapControls: {
    position: "absolute",
    right: 10,
    top: 10,
    gap: 6,
  },
  mapExpand: {
    position: "absolute",
    right: 10,
    bottom: 72,
    backgroundColor: "rgba(0,0,0,0.55)",
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  mapTapText: { color: "#fff", fontSize: 11, fontWeight: "700" },
  mapCtrlBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.line,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  mapCtrlText: { fontSize: 18, fontWeight: "700", color: colors.ink, lineHeight: 20 },
  routeLoading: {
    position: "absolute",
    left: 10,
    top: 10,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  categoryBar: {
    position: "absolute",
    top: 8,
    left: 0,
    right: 0,
    zIndex: 20,
    maxHeight: 48,
  },
  categoryBarInner: {
    paddingHorizontal: 16,
    gap: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  categoryChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.95)",
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.06)",
    ...cardShadow,
  },
  categoryChipOn: {
    backgroundColor: colors.ink,
    borderColor: colors.ink,
  },
  categoryIcon: { fontSize: 14, marginRight: 4 },
  categoryLabel: { fontSize: 14, fontWeight: "700", color: colors.ink },
  categoryLabelOn: { color: "#fff" },
  categoryHint: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 16,
    alignItems: "center",
  },
  categoryHintText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.ink,
    backgroundColor: "rgba(255,255,255,0.92)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    overflow: "hidden",
    ...cardShadow,
  },
});
