import { StyleSheet } from "react-native";
import { colors, cardShadow } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#eef2f7" },
  mapBox: { ...StyleSheet.absoluteFill },
  map: { flex: 1, backgroundColor: "#eef2f7" },
  mapFallback: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
  },
  mapFallbackText: { color: colors.muted },
  topBar: {
    position: "absolute",
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    zIndex: 4,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.94)",
    alignItems: "center",
    justifyContent: "center",
    ...cardShadow,
  },
  backText: { fontSize: 22, color: colors.ink, fontWeight: "300", marginTop: -2 },
  topTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 17,
    fontWeight: "800",
    color: colors.ink,
  },
  mapCtrls: {
    position: "absolute",
    right: 12,
    top: 110,
    gap: 8,
    zIndex: 3,
  },
  ctrlBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    ...cardShadow,
  },
  locateText: { fontSize: 11, fontWeight: "800", color: colors.ink },
  callout: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 92,
    backgroundColor: "#fff",
    borderRadius: 22,
    borderCurve: "continuous",
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    zIndex: 5,
    ...cardShadow,
  },
  calloutBody: { flex: 1, minWidth: 0 },
  calloutName: { fontSize: 16, fontWeight: "800", color: colors.ink },
  calloutSub: { marginTop: 4, fontSize: 12, color: colors.muted },
  confirmBtn: {
    backgroundColor: colors.brand,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  confirmText: { color: "#fff", fontWeight: "800", fontSize: 14 },
  searchDock: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    zIndex: 4,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 22,
    borderCurve: "continuous",
    paddingLeft: 14,
    paddingRight: 8,
    height: 52,
    ...cardShadow,
  },
  searchIcon: { fontSize: 18, color: colors.muted, marginRight: 8 },
  searchPlaceholder: { flex: 1, fontSize: 15, color: colors.muted },
  searchValue: { color: colors.ink, fontWeight: "700" },
  searchGo: {
    backgroundColor: colors.brand,
    color: "#fff",
    fontWeight: "800",
    fontSize: 14,
    overflow: "hidden",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  searchSheet: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "#fff",
    zIndex: 8,
  },
  searchHead: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingBottom: 8,
    gap: 8,
  },
  sheetBack: { fontSize: 28, color: colors.ink, width: 28, textAlign: "center" },
  searchField: {
    flex: 1,
    height: 44,
    borderRadius: 18,
    backgroundColor: colors.bgSurface,
    paddingHorizontal: 12,
    justifyContent: "center",
  },
  input: { fontSize: 16, color: colors.ink, padding: 0 },
  searchBtn: {
    backgroundColor: colors.brand,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  searchBtnText: { color: "#fff", fontWeight: "800" },
  chips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  chip: {
    backgroundColor: colors.bgSurface,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chipText: { fontSize: 13, fontWeight: "700", color: colors.ink },
  list: { paddingHorizontal: 8, paddingBottom: 40 },
  histHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  histTitle: { fontSize: 14, fontWeight: "800", color: colors.ink },
  histClear: { fontSize: 13, color: colors.muted, fontWeight: "700" },
  emptyHint: {
    textAlign: "center",
    color: colors.muted,
    marginTop: 32,
    fontSize: 14,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
  },
  rowPin: { fontSize: 16, marginRight: 10 },
  rowBody: { flex: 1, minWidth: 0 },
  rowTitle: { fontSize: 16, fontWeight: "700", color: colors.ink },
  rowSub: { marginTop: 3, fontSize: 12, color: colors.muted },
});
