import { StyleSheet } from "react-native";
import { colors, cardShadow } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#FFFFFF" },
  mapBox: { ...StyleSheet.absoluteFillObject },
  map: { flex: 1, backgroundColor: "#FFFFFF" },
  mapFallback: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  backBtn: {
    position: "absolute",
    left: 14,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.94)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 4,
    ...cardShadow,
  },
  backText: { fontSize: 22, color: colors.ink, fontWeight: "300", marginTop: -2 },
  sheetContent: {
    flex: 1,
    minHeight: 0,
    paddingHorizontal: 20,
  },
  sheetScroll: {
    flex: 1,
    minHeight: 0,
  },
  title: { fontSize: 28, fontWeight: "800", color: colors.ink },
  sub: { marginTop: 6, fontSize: 13, color: colors.muted },
  folderCard: {
    marginTop: 18,
    backgroundColor: "#F7F8FA",
    borderRadius: 22,
    borderCurve: "continuous",
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
  },
  folderBody: { flex: 1, minWidth: 0 },
  folderName: { fontSize: 18, fontWeight: "800", color: colors.ink },
  folderMeta: {
    marginTop: 8,
    fontSize: 13,
    color: colors.muted,
  },
  folderIcon: { fontSize: 42, marginLeft: 8 },
  addBtn: {
    marginHorizontal: 48,
    marginTop: 4,
    marginBottom: 8,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#111",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    ...cardShadow,
  },
  addPlus: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.6,
    borderColor: "#fff",
    color: "#fff",
    textAlign: "center",
    fontSize: 16,
    fontWeight: "700",
    lineHeight: 20,
  },
  addText: { color: "#fff", fontSize: 16, fontWeight: "800" },
  searchBar: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F4F5F7",
    borderRadius: 18,
    paddingHorizontal: 14,
    height: 44,
  },
  searchPlaceholder: { flex: 1, fontSize: 15, color: colors.muted },
  placeRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
  },
  placeStar: { fontSize: 16, marginRight: 10, color: "#E6B422" },
  placeBody: { flex: 1, minWidth: 0 },
  placeName: { fontSize: 16, fontWeight: "700", color: colors.ink },
  placeSub: { marginTop: 3, fontSize: 12, color: colors.muted },
  empty: {
    marginTop: 28,
    textAlign: "center",
    color: colors.muted,
    fontSize: 14,
  },
  modalMask: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 28,
  },
  modalCard: {
    width: "100%",
    maxWidth: 340,
    backgroundColor: "#fff",
    borderRadius: 22,
    borderCurve: "continuous",
    padding: 18,
    ...cardShadow,
  },
  modalTitle: { fontSize: 17, fontWeight: "800", color: colors.ink },
  modalInput: {
    marginTop: 14,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#F4F5F7",
    paddingHorizontal: 12,
    fontSize: 16,
    color: colors.ink,
  },
  modalRow: {
    marginTop: 16,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
  },
  modalCancel: { fontSize: 15, color: colors.muted, fontWeight: "700" },
  modalOk: { fontSize: 15, color: colors.brandHot, fontWeight: "800" },
  searchSheet: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#fff",
    zIndex: 12,
  },
  searchHead: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingBottom: 8,
    gap: 8,
  },
  sheetBack: { fontSize: 28, color: colors.ink, width: 28, textAlign: "center" },
  searchField: {
    flex: 1,
    height: 44,
    borderRadius: 18,
    backgroundColor: "#F4F5F7",
    paddingHorizontal: 12,
    justifyContent: "center",
  },
  input: { fontSize: 16, color: colors.ink, padding: 0 },
  searchBtn: {
    backgroundColor: colors.brand,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  searchBtnText: { color: "#fff", fontWeight: "800" },
  row: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
  },
  rowPin: { fontSize: 16, marginRight: 10 },
  rowBody: { flex: 1, minWidth: 0 },
  rowTitle: { fontSize: 16, fontWeight: "700", color: colors.ink },
  rowSub: { marginTop: 3, fontSize: 12, color: colors.muted },
  list: { paddingBottom: 40 },
});
