import { StyleSheet } from "react-native";
import { colors, cardShadow } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#F4F5F7" },
  menuBtn: {
    position: "absolute",
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    ...cardShadow,
  },
  menuIcon: { fontSize: 18, color: colors.ink, fontWeight: "800" },
  profile: { alignItems: "center", paddingTop: 12, paddingBottom: 8 },
  avatar: {
    width: 168,
    height: 168,
    borderRadius: 36,
    borderCurve: "continuous",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    ...cardShadow,
  },
  avatarText: { fontSize: 64, fontWeight: "800", color: colors.brandHot },
  username: {
    marginTop: 16,
    fontSize: 26,
    fontWeight: "800",
    color: colors.ink,
  },
  hint: { marginTop: 8, fontSize: 13, color: colors.brandHot, fontWeight: "700" },
  grid: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 18,
    marginTop: 22,
  },
  miniCard: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 28,
    borderCurve: "continuous",
    padding: 16,
    minHeight: 148,
    ...cardShadow,
  },
  miniIcon: { fontSize: 36, marginBottom: 18 },
  miniTitle: { fontSize: 16, fontWeight: "800", color: colors.ink },
  miniSub: { marginTop: 4, fontSize: 12, color: colors.muted },
  footCard: {
    marginHorizontal: 18,
    marginTop: 12,
    backgroundColor: "#EEF3FF",
    borderRadius: 28,
    borderCurve: "continuous",
    padding: 18,
    minHeight: 132,
    overflow: "hidden",
    ...cardShadow,
  },
  footTitle: { fontSize: 18, fontWeight: "800", color: colors.ink },
  footMeta: { marginTop: 6, fontSize: 13, color: colors.muted },
  footLoc: {
    position: "absolute",
    right: 16,
    bottom: 18,
    maxWidth: "46%",
    fontSize: 11,
    color: "#8A94A8",
    textAlign: "right",
  },
  footDeco: {
    position: "absolute",
    right: -20,
    top: -30,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(255,255,255,0.45)",
  },
  checkDot: {
    position: "absolute",
    left: "42%",
    bottom: 18,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#4FC3F7",
    alignItems: "center",
    justifyContent: "center",
  },
  checkDotText: { color: "#fff", fontSize: 14, fontWeight: "800" },
  artEmpty: {
    marginTop: 28,
    fontSize: 22,
    fontFamily: "Georgia",
    fontStyle: "italic",
    color: "#8A94A8",
    letterSpacing: 1,
  },
  overviewRoot: { flex: 1, backgroundColor: "#F4F5F7" },
  overviewHead: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  back: { fontSize: 16, color: colors.ink, fontWeight: "700", width: 48 },
  overviewTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 20,
    fontWeight: "800",
    color: colors.ink,
  },
  overviewScroll: { paddingHorizontal: 16, paddingBottom: 88, gap: 12 },
  statGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  statCard: {
    width: "48%",
    flexGrow: 1,
    backgroundColor: "#fff",
    borderRadius: 24,
    borderCurve: "continuous",
    padding: 16,
    minHeight: 100,
    ...cardShadow,
  },
  statSeason: { backgroundColor: "#E7F6DC" },
  statNum: { fontSize: 28, fontWeight: "800", color: colors.ink },
  statLabel: { marginTop: 6, fontSize: 13, color: colors.muted },
  cardBlue: {
    backgroundColor: "#DCEBFF",
    borderRadius: 24,
    borderCurve: "continuous",
    padding: 18,
    ...cardShadow,
  },
  cardLav: {
    backgroundColor: "#E8E0F4",
    borderRadius: 24,
    borderCurve: "continuous",
    padding: 18,
    ...cardShadow,
  },
  cardBrown: {
    backgroundColor: "#5C4033",
    borderRadius: 24,
    borderCurve: "continuous",
    padding: 18,
    ...cardShadow,
  },
  cardMint: {
    backgroundColor: "#CDEBD9",
    borderRadius: 24,
    borderCurve: "continuous",
    paddingTop: 14,
    paddingBottom: 10,
    paddingHorizontal: 14,
    overflow: "hidden",
    ...cardShadow,
  },
  cardGold: {
    backgroundColor: "#F0D48A",
    borderRadius: 24,
    borderCurve: "continuous",
    padding: 18,
    ...cardShadow,
  },
  cardKicker: { fontSize: 13, fontWeight: "700", color: "#4A5A78" },
  cardCity: { marginTop: 8, fontSize: 28, fontWeight: "800", color: colors.ink },
  cardSub: { marginTop: 8, fontSize: 13, color: "#5A6578", lineHeight: 20 },
  dateBadge: {
    position: "absolute",
    right: 14,
    top: 14,
    backgroundColor: "#F6E08B",
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  dateBadgeText: { fontSize: 12, fontWeight: "800", color: colors.ink },
  altRow: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  altNum: { fontSize: 22, fontWeight: "800", color: "#5A4A78" },
  brownTitle: { fontSize: 13, fontWeight: "700", color: "#E8D5C4" },
  brownName: {
    marginTop: 16,
    fontSize: 18,
    fontWeight: "800",
    color: "#fff",
    textAlign: "center",
  },
  mintTitle: { fontSize: 14, fontWeight: "800", color: "#2E5C4A" },
  mintHead: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 4,
  },
  mintChevrons: {
    flex: 1,
    fontSize: 13,
    fontWeight: "800",
    color: "#2E5C4A",
    letterSpacing: 0.4,
  },
  mintCount: {
    marginLeft: 8,
    fontSize: 28,
    fontWeight: "800",
    color: "#2E5C4A",
    fontVariant: ["tabular-nums"],
  },
  mintDivider: {
    position: "absolute",
    top: 8,
    bottom: 8,
    left: "50%",
    width: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(46,92,74,0.12)",
  },
  mintMapWrap: {
    marginTop: 8,
  },
  goldInner: {
    marginTop: 12,
    backgroundColor: "#4A3728",
    borderRadius: 16,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  goldLabel: { fontSize: 22, fontWeight: "800", color: "#F6E08B" },
  goldNum: { fontSize: 28, fontWeight: "800", color: "#fff" },
  overviewEmptyWrap: {
    paddingTop: 12,
    alignItems: "flex-start",
    paddingHorizontal: 0,
    paddingBottom: 88,
  },
  overviewArt: {
    marginTop: 48,
    alignSelf: "center",
    fontSize: 26,
    textAlign: "center",
  },
  mapLink: {
    marginTop: 8,
    alignSelf: "center",
    paddingVertical: 10,
  },
  mapLinkText: { fontSize: 14, fontWeight: "700", color: colors.brandHot },
  addBubble: {
    alignSelf: "flex-start",
    marginLeft: 18,
    marginBottom: 12,
    backgroundColor: "#fff",
    borderRadius: 22,
    borderCurve: "continuous",
    paddingHorizontal: 20,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: "#D7EAF8",
    ...cardShadow,
  },
  addBubbleText: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.brandHot,
  },
});
