import { Platform, StyleSheet } from "react-native";
import { colors, cardShadow } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#eef2f7" },
  map: { ...StyleSheet.absoluteFill },

  // 顶部浮层
  topOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 16,
    paddingBottom: 8,
    zIndex: 10,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 30, borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.92)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    ...cardShadow,
  },
  backText: { fontSize: 22, color: colors.ink, fontWeight: "300", marginTop: -2 },
  topCityBlock: { flex: 1, paddingTop: 4 },
  topCityName: { fontSize: 22, fontWeight: "800", color: colors.ink },
  topCitySubRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 2,
  },
  topCitySub: { fontSize: 13, color: colors.muted },
  searchBtn: {
    width: 40,
    height: 40,
    borderRadius: 30, borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.92)",
    alignItems: "center",
    justifyContent: "center",
    ...cardShadow,
  },
  searchIcon: { fontSize: 18 },

  // 分类筛选
  filterBar: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 10,
  },
  filterScroll: {
    paddingHorizontal: 16,
    gap: 10,
    flexDirection: "row",
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.95)",
    borderRadius: 32, borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 10,
    ...cardShadow,
  },
  filterChipOn: {
    backgroundColor: colors.ink,
  },
  filterIcon: { fontSize: 16, marginRight: 6 },
  filterLabel: { fontSize: 14, fontWeight: "700", color: colors.ink },
  filterLabelOn: { color: "#fff" },

  // 定位按钮
  locateBtn: {
    position: "absolute",
    right: 16,
    width: 40,
    height: 40,
    borderRadius: 30, borderCurve: "continuous",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
    borderWidth: 1,
    borderColor: colors.line,
    ...cardShadow,
  },
  locateIcon: { fontSize: 18 },

  // 底部抽屉
  bottomSheetRoot: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
  },
  bottomSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34, borderCurve: "continuous",
    ...cardShadow,
  },
  sheetDragZone: {
    paddingTop: 10,
    paddingBottom: 6,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  sheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 12, borderCurve: "continuous",
    backgroundColor: "#bbb",
  },
  sheetBody: {
    flex: 1,
    minHeight: 0,
  },
  sheetScroll: {
    flex: 1,
    minHeight: 0,
  },
  sheetTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.ink,
    paddingHorizontal: 20,
    marginBottom: 8,
    marginTop: 4,
  },
  sheetDesc: {
    fontSize: 13,
    color: colors.muted,
    lineHeight: 20,
    paddingHorizontal: 20,
    marginBottom: 14,
  },
  sheetList: { paddingHorizontal: 16, paddingBottom: 8 },
  itemCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.card,
    borderRadius: 26, borderCurve: "continuous",
    padding: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.line,
  },
  itemThumb: {
    width: 64,
    height: 64,
    borderRadius: 22, borderCurve: "continuous",
    backgroundColor: colors.brandSoft,
    overflow: "hidden",
  },
  itemThumbImg: { width: "100%", height: "100%" },
  itemBody: { flex: 1, marginLeft: 12, marginRight: 8 },
  itemName: { fontSize: 16, fontWeight: "800", color: colors.ink, marginBottom: 4 },
  itemMeta: { fontSize: 12, color: colors.muted },
  itemAdd: {
    width: 36,
    height: 36,
    borderRadius: 28, borderCurve: "continuous",
    borderWidth: 1.5,
    borderColor: colors.line,
    alignItems: "center",
    justifyContent: "center",
  },
  itemAddText: { fontSize: 20, color: colors.ink, fontWeight: "300", marginTop: -2 },
  genBtn: {
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 8,
    backgroundColor: colors.brand,
    borderRadius: 24, borderCurve: "continuous",
    paddingVertical: 13,
    alignItems: "center",
  },
  genBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  xhsBtn: {
    marginHorizontal: 16,
    marginTop: 2,
    marginBottom: 6,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF5F5",
    borderRadius: 24, borderCurve: "continuous",
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#FFD6D6",
  },
  xhsBtnIcon: { fontSize: 16, marginRight: 8 },
  xhsBtnText: { flex: 1, fontSize: 14, fontWeight: "700", color: "#E6162D" },
  xhsBtnArrow: { fontSize: 18, color: "#E6162D", fontWeight: "300" },

  // 加载 / 错误 / 空态
  overlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: colors.bg,
    zIndex: 20,
  },
  overlayHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingBottom: 10,
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  overlayTitle: { fontSize: 18, fontWeight: "800", color: colors.ink, marginLeft: 4 },
  center: { flex: 1, justifyContent: "center", alignItems: "center", padding: 40 },
  loadingText: { marginTop: 12, fontSize: 14, color: colors.muted, textAlign: "center" },
  streamPreviewScroll: {
    marginTop: 16,
    maxHeight: 220,
    width: "100%",
    backgroundColor: "rgba(255,255,255,0.92)",
    borderRadius: 24, borderCurve: "continuous",
    ...cardShadow,
  },
  streamPreviewContent: { padding: 14 },
  streamPreviewText: {
    fontSize: 13,
    lineHeight: 20,
    color: colors.ink,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  streamPreviewCursor: { fontSize: 13, color: colors.brand, marginTop: 4 },
  errorText: { fontSize: 15, color: colors.danger, textAlign: "center", lineHeight: 22 },
  emptyText: { fontSize: 14, color: colors.muted, textAlign: "center" },
  retryBtn: {
    marginTop: 20,
    backgroundColor: colors.brand,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 22, borderCurve: "continuous",
  },
  retryText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  mapLoading: {
    ...StyleSheet.absoluteFill,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#eef2f7",
  },

  // POI 详情弹层
  detailRoot: { flex: 1, justifyContent: "flex-end" },
  detailBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  detailSheet: {
    maxHeight: "88%",
    backgroundColor: "#fff",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30, borderCurve: "continuous",
    overflow: "hidden",
  },
  detailHead: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 12,
  },
  detailHeadMain: { flex: 1, paddingRight: 12 },
  detailTitle: { fontSize: 22, fontWeight: "800", color: colors.ink, lineHeight: 30 },
  detailTags: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
  detailTag: {
    backgroundColor: "#f3f3f3",
    borderRadius: 18, borderCurve: "continuous",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  detailTagText: { fontSize: 12, color: colors.muted, fontWeight: "600" },
  detailTagBlue: { backgroundColor: colors.brandSoft },
  detailTagBlueText: { fontSize: 12, color: colors.brandHot, fontWeight: "700" },
  detailClose: {
    width: 32,
    height: 32,
    borderRadius: 26, borderCurve: "continuous",
    backgroundColor: "#f5f5f5",
    alignItems: "center",
    justifyContent: "center",
  },
  detailCloseText: { fontSize: 14, color: colors.muted, fontWeight: "700" },
  detailGallery: { paddingHorizontal: 20, gap: 10, paddingBottom: 16 },
  detailGalleryImg: { height: 160, borderRadius: 26, borderCurve: "continuous", marginRight: 10 },
  detailSection: { paddingHorizontal: 20, marginBottom: 18 },
  detailSectionHead: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
  detailSectionTitle: { fontSize: 17, fontWeight: "800", color: colors.ink },
  aiBadge: {
    marginLeft: 8,
    backgroundColor: "#f0f0f0",
    borderRadius: 16, borderCurve: "continuous",
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  aiBadgeText: { fontSize: 11, color: colors.muted, fontWeight: "600" },
  detailDesc: { fontSize: 14, color: colors.ink, lineHeight: 22 },
  reviewCardGreen: {
    backgroundColor: "#E8F8F0",
    borderRadius: 26, borderCurve: "continuous",
    padding: 14,
    marginTop: 10,
    marginBottom: 10,
    position: "relative",
    overflow: "hidden",
  },
  reviewCardPink: {
    backgroundColor: "#FFF0F3",
    borderRadius: 26, borderCurve: "continuous",
    padding: 14,
    position: "relative",
    overflow: "hidden",
  },
  reviewStickerGreen: {
    position: "absolute",
    top: 8,
    right: 10,
    fontSize: 18,
    fontWeight: "800",
    color: "rgba(76,175,80,0.35)",
    transform: [{ rotate: "-12deg" }],
  },
  reviewStickerPink: {
    position: "absolute",
    top: 8,
    right: 10,
    fontSize: 16,
    fontWeight: "800",
    color: "rgba(233,30,99,0.28)",
    transform: [{ rotate: "8deg" }],
  },
  reviewPoint: { fontSize: 14, color: colors.ink, lineHeight: 22, marginBottom: 6 },
  reviewLabel: { fontWeight: "800", color: colors.ink },
  sourceRow: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  sourceLabel: { fontSize: 13, color: colors.muted, fontWeight: "600" },
  sourcePill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f7f7f7",
    borderRadius: 30, borderCurve: "continuous",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: colors.line,
  },
  xhsLogo: {
    width: 18,
    height: 18,
    borderRadius: 14, borderCurve: "continuous",
    backgroundColor: "#E6162D",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 6,
  },
  xhsLogoText: { fontSize: 10, color: "#fff", fontWeight: "800" },
  sourcePillText: { fontSize: 13, color: colors.ink, fontWeight: "700" },
  sourceDropdown: { fontSize: 12, color: colors.muted, marginLeft: 4 },
  infoList: {
    marginHorizontal: 20,
    marginBottom: 16,
    borderRadius: 26, borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    overflow: "hidden",
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  infoRowLast: { borderBottomWidth: 0 },
  infoIcon: { fontSize: 18, marginRight: 12 },
  infoBody: { flex: 1 },
  infoTitle: { fontSize: 15, fontWeight: "700", color: colors.ink },
  infoSub: { fontSize: 12, color: colors.muted, marginTop: 2 },
  infoChevron: { fontSize: 18, color: colors.muted, fontWeight: "300" },
  detailActions: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingTop: 10,
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  detailActionBtn: {
    flex: 1,
    borderRadius: 34, borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    paddingVertical: 12,
    alignItems: "center",
  },
  detailActionPrimary: { backgroundColor: colors.ink, borderColor: colors.ink },
  detailActionChecked: { backgroundColor: colors.brandSoft, borderColor: colors.brand },
  detailActionText: { fontSize: 14, fontWeight: "700", color: colors.ink },
  detailActionTextChecked: { color: colors.brandHot },
  detailActionTextPrimary: { color: "#fff" },
});
