import { StyleSheet } from "react-native";
import { colors, cardShadow } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  scrollContent: { paddingBottom: 40 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingBottom: 10,
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  backBtn: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  backText: { fontSize: 22, color: colors.ink, fontWeight: "300" },
  headerTitle: { fontSize: 18, fontWeight: "800", color: colors.ink, marginLeft: 4 },
  hero: {
    height: 180,
    backgroundColor: colors.brandSoft,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  heroCity: { fontSize: 32, fontWeight: "800", color: colors.ink },
  heroSub: { fontSize: 13, color: colors.muted, marginTop: 6 },
  center: { flex: 1, justifyContent: "center", alignItems: "center", padding: 40 },
  loadingText: { marginTop: 12, fontSize: 14, color: colors.muted },
  errorText: { fontSize: 15, color: colors.danger, textAlign: "center", lineHeight: 22 },
  retryBtn: {
    marginTop: 20,
    backgroundColor: colors.brand,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  retryText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  section: { marginTop: 24, paddingHorizontal: 20 },
  sectionHead: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  sectionIcon: { fontSize: 18, marginRight: 8 },
  sectionTitle: { fontSize: 18, fontWeight: "800", color: colors.ink },
  itemCard: {
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    ...cardShadow,
  },
  itemName: { fontSize: 16, fontWeight: "700", color: colors.ink, marginBottom: 6 },
  itemDesc: { fontSize: 14, color: colors.muted, lineHeight: 21 },
  emptyText: { fontSize: 14, color: colors.muted, textAlign: "center", marginTop: 20 },
  genBtn: {
    marginHorizontal: 20,
    marginTop: 28,
    backgroundColor: colors.brand,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    ...cardShadow,
  },
  genBtnText: { color: "#fff", fontWeight: "700", fontSize: 16 },
});
