import { StyleSheet } from "react-native";
import { colors } from "../../theme";

export const styles = StyleSheet.create({
  card: {
    marginTop: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d6e4ff",
    backgroundColor: "#f0f7ff",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  cardTop: { flexDirection: "row", alignItems: "center", gap: 8 },
  badge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#1a66ff",
    alignItems: "center",
    justifyContent: "center",
  },
  badgeText: { color: "#fff", fontSize: 11, fontWeight: "800" },
  cardSummary: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: "#1a66ff",
  },
  cardCta: { fontSize: 12, fontWeight: "700", color: "#1a66ff" },
  cardSub: { marginTop: 4, fontSize: 11, color: colors.muted },
  modalRoot: { flex: 1, justifyContent: "flex-end" },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.45)",
  } as const,
  sheet: {
    maxHeight: "92%",
    backgroundColor: "#fff",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    overflow: "hidden",
  },
  edgeHint: {
    position: "absolute",
    left: 0,
    top: 80,
    bottom: 80,
    width: 3,
    borderRadius: 2,
    backgroundColor: "rgba(26,102,255,0.35)",
    zIndex: 2,
  },
  sheetHead: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 4,
  },
  backChevron: {
    fontSize: 28,
    lineHeight: 28,
    fontWeight: "300",
    color: colors.brandHot,
    marginTop: -2,
  },
  backText: { fontSize: 15, fontWeight: "700", color: colors.brandHot },
  sheetTitle: { fontSize: 16, fontWeight: "800", color: colors.ink },
  sheetSub: { marginTop: 2, fontSize: 12, color: colors.muted },
  close: { fontSize: 14, fontWeight: "700", color: colors.muted },
  swipeTip: {
    paddingHorizontal: 16,
    paddingTop: 6,
    fontSize: 11,
    color: colors.muted,
  },
  tabs: { flexDirection: "row", gap: 8, paddingHorizontal: 12, paddingTop: 8 },
  tab: {
    flex: 1,
    borderRadius: 20,
    paddingVertical: 8,
    alignItems: "center",
    backgroundColor: colors.bg,
  },
  tabOn: { backgroundColor: "#1a66ff" },
  tabText: { fontSize: 13, fontWeight: "700", color: colors.ink },
  tabTextOn: { color: "#fff" },
  mapBox: {
    marginHorizontal: 12,
    marginTop: 12,
    height: 220,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#eef2f7",
  },
  mapFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  mapFallbackText: { fontSize: 12, color: colors.muted, textAlign: "center" },
  mapLoading: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.45)",
  } as const,
  mapControls: {
    position: "absolute",
    right: 8,
    bottom: 8,
    gap: 6,
  },
  ctrlBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.line,
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
  },
  ctrlText: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.ink,
    lineHeight: 20,
  },
  locateBtn: { marginTop: 2 },
  locateText: { fontSize: 11, fontWeight: "800", color: "#1a66ff" },
  steps: { paddingHorizontal: 16, paddingTop: 12 },
  stepRow: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  stepTitle: { fontSize: 14, fontWeight: "700", color: colors.ink },
  stepDesc: { marginTop: 4, fontSize: 12, color: colors.muted, lineHeight: 18 },
  hint: { paddingVertical: 20, textAlign: "center", color: colors.muted },
  error: { color: colors.danger, marginBottom: 8 },
});
