import { StyleSheet } from "react-native";
import { colors } from "../../theme";

export const styles = StyleSheet.create({
  panel: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: colors.ink,
    lineHeight: 36,
    marginBottom: 8,
  },
  heroHint: {
    fontSize: 13,
    color: colors.muted,
    marginBottom: 20,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#dbeafe",
    paddingHorizontal: 14,
    paddingVertical: 4,
    marginBottom: 12,
  },
  searchIcon: {
    fontSize: 18,
    color: colors.brand,
    marginRight: 10,
    fontWeight: "700",
  },
  searchInput: {
    flex: 1,
    fontSize: 17,
    color: colors.ink,
    paddingVertical: 12,
  },
  clearChip: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#e5e7eb",
    alignItems: "center",
    justifyContent: "center",
  },
  clearChipText: {
    fontSize: 16,
    color: "#6b7280",
    lineHeight: 18,
  },
  suggestList: {
    flex: 1,
  },
  smartRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  smartRowMain: { flex: 1 },
  smartRowTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.ink,
  },
  smartRowSub: {
    fontSize: 13,
    color: colors.muted,
    marginTop: 4,
  },
  smartRowGo: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.brand,
    alignItems: "center",
    justifyContent: "center",
  },
  smartRowGoText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
  },
  cityRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  cityRowMain: { flex: 1 },
  cityRowTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.ink,
  },
  cityRowSub: {
    fontSize: 12,
    color: colors.muted,
    marginTop: 2,
  },
  cityRowPlus: {
    fontSize: 22,
    color: colors.muted,
    fontWeight: "300",
    paddingHorizontal: 8,
  },
  emptyHint: {
    fontSize: 14,
    color: colors.muted,
    textAlign: "center",
    marginTop: 24,
  },
  confirmCard: {
    marginTop: 12,
    backgroundColor: colors.card,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 20,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  confirmHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  confirmLabelWrap: {
    flex: 1,
    marginRight: 12,
  },
  confirmLabel: {
    fontSize: 13,
    color: colors.muted,
  },
  replaceBtn: {
    fontSize: 13,
    color: colors.brand,
    fontWeight: "600",
  },
  replaceBtnDisabled: {
    color: colors.muted,
  },
  expandedHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  expandedLabel: {
    fontSize: 12,
    color: colors.muted,
    fontWeight: "600",
  },
  modelLink: {
    fontSize: 12,
    color: colors.brand,
    fontWeight: "600",
  },
  optimizeLoading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  optimizeLoadingText: {
    fontSize: 13,
    color: colors.muted,
  },
  optimizeError: {
    fontSize: 12,
    color: colors.danger,
    marginBottom: 8,
  },
  expandedQueryInput: {
    fontSize: 18,
    fontWeight: "600",
    color: colors.ink,
    lineHeight: 26,
    minHeight: 72,
    textAlignVertical: "top",
    padding: 0,
    marginBottom: 10,
  },
  confirmMeta: {
    fontSize: 13,
    color: colors.muted,
    marginBottom: 20,
  },
  confirmBtn: {
    backgroundColor: colors.ink,
    borderRadius: 24,
    paddingVertical: 14,
    alignItems: "center",
  },
  confirmBtnDisabled: {
    opacity: 0.45,
  },
  confirmBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
});
