import { StyleSheet } from "react-native";
import { colors } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    backgroundColor: colors.card,
  },
  headerLeft: { flex: 1 },
  headerTitle: { fontSize: 18, fontWeight: "800", color: colors.ink },
  headerSub: { fontSize: 11, color: colors.muted, marginTop: 2 },
  clearBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: colors.brandSoft,
  },
  clearText: { fontSize: 12, color: colors.brandHot, fontWeight: "600" },
  list: { flex: 1, paddingHorizontal: 12, paddingTop: 8 },
  welcomeWrap: { flex: 1, justifyContent: "center", alignItems: "center", padding: 24 },
  welcomeEmoji: { fontSize: 48, marginBottom: 16 },
  welcomeText: {
    fontSize: 14,
    color: colors.muted,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 24,
    paddingHorizontal: 12,
  },
  quickRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, justifyContent: "center" },
  quickChip: {
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  quickChipText: { fontSize: 12, color: colors.ink, fontWeight: "600" },
  msgRow: { flexDirection: "row", marginBottom: 12 },
  msgUserRow: { justifyContent: "flex-end" },
  msgBubble: {
    maxWidth: "82%",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  msgUser: { backgroundColor: colors.brand },
  msgAI: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
  },
  msgUserText: { fontSize: 15, color: "#fff", lineHeight: 22 },
  msgAIText: { fontSize: 15, color: colors.ink, lineHeight: 22 },
  reasoningBox: {
    backgroundColor: "#f5f0e8",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  reasoningLabel: {
    fontSize: 11,
    color: colors.muted,
    fontWeight: "700",
    marginBottom: 4,
  },
  reasoningText: {
    fontSize: 13,
    color: colors.muted,
    lineHeight: 19,
  },
  loadingDot: {
    alignSelf: "flex-start",
    marginLeft: 4,
    marginBottom: 12,
  },
  inputBar: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.card,
    gap: 8,
  },
  input: {
    flex: 1,
    backgroundColor: colors.bg,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 15,
    color: colors.ink,
    maxHeight: 100,
  },
  sendBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.brand,
    alignItems: "center",
    justifyContent: "center",
  },
  sendDisabled: { opacity: 0.4 },
  sendText: { color: "#fff", fontWeight: "800", fontSize: 14 },
  stopBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.danger,
    alignItems: "center",
    justifyContent: "center",
  },
  stopText: { color: "#fff", fontWeight: "800", fontSize: 12 },
});
