import { Platform, StyleSheet } from "react-native";
import { colors } from "../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    backgroundColor: colors.card,
  },
  headerLeft: { flex: 1 },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  backLink: { fontSize: 14, color: colors.brand, fontWeight: "600", marginBottom: 4 },
  smartPlanBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 30, borderCurve: "continuous",
    backgroundColor: colors.ink,
  },
  smartPlanBtnText: { fontSize: 13, color: "#fff", fontWeight: "700" },
  headerTitle: { fontSize: 18, fontWeight: "800", color: colors.ink },
  headerSub: { fontSize: 11, color: colors.muted, marginTop: 2 },
  clearBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 18, borderCurve: "continuous",
    backgroundColor: colors.brandSoft,
  },
  clearText: { fontSize: 12, color: colors.brandHot, fontWeight: "600" },
  historyBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 18, borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.9)",
    borderWidth: 1,
    borderColor: colors.line,
  },
  historyBtnText: { fontSize: 12, color: colors.ink, fontWeight: "600" },
  list: { flex: 1, paddingHorizontal: 12, paddingTop: 8 },
  welcomeWrap: { flex: 1, justifyContent: "center", alignItems: "center", padding: 24 },
  welcomeEmoji: { fontSize: 48, marginBottom: 16 },
  welcomeText: {
    fontSize: 14,
    color: colors.muted,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 24,
    paddingHorizontal: 12,
  },
  quickRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, justifyContent: "center" },
  smartPlanEntry: {
    width: "100%",
    backgroundColor: colors.ink,
    borderRadius: 26, borderCurve: "continuous",
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: "center",
    marginBottom: 4,
  },
  smartPlanEntryText: { fontSize: 15, color: "#fff", fontWeight: "700" },
  quickChip: {
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    borderRadius: 26, borderCurve: "continuous",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  quickChipText: { fontSize: 12, color: colors.ink, fontWeight: "600" },
  msgRow: { flexDirection: "row", marginBottom: 12 },
  msgUserRow: { justifyContent: "flex-end" },
  msgBubble: {
    maxWidth: "82%",
    borderRadius: 28, borderCurve: "continuous",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  msgUser: { backgroundColor: colors.brand },
  msgAI: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
  },
  msgUserText: { fontSize: 15, color: "#fff", lineHeight: 22 },
  msgAIText: { fontSize: 15, color: colors.ink, lineHeight: 22 },
  reasoningBox: {
    backgroundColor: "#f5f0e8",
    borderRadius: 20, borderCurve: "continuous",
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  reasoningLabel: {
    fontSize: 11,
    color: colors.muted,
    fontWeight: "700",
    marginBottom: 4,
  },
  reasoningText: {
    fontSize: 13,
    color: colors.muted,
    lineHeight: 19,
  },
  loadingDot: {
    alignSelf: "flex-start",
    marginLeft: 4,
    marginBottom: 12,
  },
  inputBar: {
    paddingHorizontal: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.card,
    gap: 8,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  input: {
    flex: 1,
    backgroundColor: colors.bg,
    borderRadius: 26, borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 14,
    paddingTop: Platform.OS === "ios" ? 12 : 10,
    paddingBottom: Platform.OS === "ios" ? 12 : 10,
    fontSize: 16,
    lineHeight: 22,
    color: colors.ink,
  },
  sendBtn: {
    width: 42,
    height: 42,
    borderRadius: 30, borderCurve: "continuous",
    backgroundColor: colors.brand,
    alignItems: "center",
    justifyContent: "center",
  },
  sendDisabled: { opacity: 0.4 },
  sendText: { color: "#fff", fontWeight: "800", fontSize: 14 },
  stopBtn: {
    width: 42,
    height: 42,
    borderRadius: 30, borderCurve: "continuous",
    backgroundColor: colors.danger,
    alignItems: "center",
    justifyContent: "center",
  },
  stopText: { color: "#fff", fontWeight: "800", fontSize: 12 },
  // 模型按钮（弹窗样式已抽到 components/ModelPicker）
  modelBtn: {
    alignSelf: "flex-start",
    height: 32,
    paddingHorizontal: 10,
    borderRadius: 20, borderCurve: "continuous",
    backgroundColor: colors.brandSoft,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.brand,
  },
  modelBtnText: { fontSize: 12, fontWeight: "700", color: colors.brandHot },
});
